/**
 * PostgreSQL-compatible error raised by the in-memory engine.
 *
 * Carries the same diagnostic fields the server sends in an ErrorResponse, so the driver
 * adapters can surface them exactly like `pg`'s `DatabaseError` / postgres.js' `PostgresError`.
 */
export interface PgErrorFields {
  detail?: string;
  hint?: string;
  position?: number;
  where?: string;
  schema?: string;
  table?: string;
  column?: string;
  dataType?: string;
  constraint?: string;
  routine?: string;
  internalQuery?: string;
  internalPosition?: number;
  noPosition?: boolean;
}

export class PgError extends Error {
  readonly code: string;
  readonly severity: string;
  detail?: string;
  hint?: string;
  position?: number;
  where?: string;
  schema?: string;
  table?: string;
  column?: string;
  dataType?: string;
  constraint?: string;
  routine?: string;
  internalQuery?: string;
  internalPosition?: number;
  /** reported without a query position even when raised while analyzing a positioned node */
  noPosition?: boolean;

  constructor(code: string, message: string, fields?: PgErrorFields, severity = 'ERROR') {
    super(message);
    this.name = 'PgError';
    this.code = code;
    this.severity = severity;
    if (fields) {
      Object.assign(this, fields);
    }
    Object.setPrototypeOf(this, PgError.prototype);
  }
}

/** SQLSTATE codes used by the engine. */
export const SqlState = {
  SUCCESSFUL_COMPLETION: '00000',
  WARNING: '01000',
  NO_DATA: '02000',
  FEATURE_NOT_SUPPORTED: '0A000',
  CARDINALITY_VIOLATION: '21000',
  DATA_EXCEPTION: '22000',
  ARRAY_SUBSCRIPT_ERROR: '2202E',
  CHARACTER_NOT_IN_REPERTOIRE: '22021',
  DATETIME_FIELD_OVERFLOW: '22008',
  DIVISION_BY_ZERO: '22012',
  ERROR_IN_ASSIGNMENT: '22005',
  ESCAPE_CHARACTER_CONFLICT: '2200B',
  INDICATOR_OVERFLOW: '22022',
  INTERVAL_FIELD_OVERFLOW: '22015',
  INVALID_ARGUMENT_FOR_LOG: '2201E',
  INVALID_ARGUMENT_FOR_NTILE: '22014',
  INVALID_ARGUMENT_FOR_NTH_VALUE: '22016',
  INVALID_ARGUMENT_FOR_POWER_FUNCTION: '2201F',
  INVALID_ARGUMENT_FOR_WIDTH_BUCKET_FUNCTION: '2201G',
  INVALID_CHARACTER_VALUE_FOR_CAST: '22018',
  INVALID_DATETIME_FORMAT: '22007',
  INVALID_ESCAPE_CHARACTER: '22019',
  INVALID_ESCAPE_OCTET: '2200D',
  INVALID_ESCAPE_SEQUENCE: '22025',
  NONSTANDARD_USE_OF_ESCAPE_CHARACTER: '22P06',
  INVALID_INDICATOR_PARAMETER_VALUE: '22010',
  INVALID_PARAMETER_VALUE: '22023',
  INVALID_PRECEDING_OR_FOLLOWING_SIZE: '22013',
  INVALID_REGULAR_EXPRESSION: '2201B',
  INVALID_ROW_COUNT_IN_LIMIT_CLAUSE: '2201W',
  INVALID_ROW_COUNT_IN_RESULT_OFFSET_CLAUSE: '2201X',
  INVALID_TIME_ZONE_DISPLACEMENT_VALUE: '22009',
  INVALID_USE_OF_ESCAPE_CHARACTER: '2200C',
  MOST_SPECIFIC_TYPE_MISMATCH: '2200G',
  NULL_VALUE_NOT_ALLOWED: '22004',
  NULL_VALUE_NO_INDICATOR_PARAMETER: '22002',
  NUMERIC_VALUE_OUT_OF_RANGE: '22003',
  SEQUENCE_GENERATOR_LIMIT_EXCEEDED: '2200H',
  STRING_DATA_LENGTH_MISMATCH: '22026',
  STRING_DATA_RIGHT_TRUNCATION: '22001',
  SUBSTRING_ERROR: '22011',
  TRIM_ERROR: '22027',
  UNTERMINATED_C_STRING: '22024',
  ZERO_LENGTH_CHARACTER_STRING: '2200F',
  FLOATING_POINT_EXCEPTION: '22P01',
  INVALID_TEXT_REPRESENTATION: '22P02',
  INVALID_BINARY_REPRESENTATION: '22P03',
  BAD_COPY_FILE_FORMAT: '22P04',
  UNTRANSLATABLE_CHARACTER: '22P05',
  INVALID_JSON_TEXT: '22P02',
  SQL_JSON_OBJECT_NOT_FOUND: '2203C',
  SQL_JSON_SCALAR_REQUIRED: '2203F',
  INTEGRITY_CONSTRAINT_VIOLATION: '23000',
  RESTRICT_VIOLATION: '23001',
  NOT_NULL_VIOLATION: '23502',
  FOREIGN_KEY_VIOLATION: '23503',
  UNIQUE_VIOLATION: '23505',
  CHECK_VIOLATION: '23514',
  EXCLUSION_VIOLATION: '23P01',
  INVALID_CURSOR_STATE: '24000',
  INVALID_TRANSACTION_STATE: '25000',
  ACTIVE_SQL_TRANSACTION: '25001',
  NO_ACTIVE_SQL_TRANSACTION: '25P01',
  IN_FAILED_SQL_TRANSACTION: '25P02',
  READ_ONLY_SQL_TRANSACTION: '25006',
  INVALID_SQL_STATEMENT_NAME: '26000',
  INVALID_TRANSACTION_TERMINATION: '2D000',
  PROTOCOL_VIOLATION: '08P01',
  DEPENDENT_OBJECTS_STILL_EXIST: '2BP01',
  INVALID_CURSOR_NAME: '34000',
  INVALID_SCHEMA_NAME: '3F000',
  UNDEFINED_SCHEMA: '3F000',
  TRANSACTION_ROLLBACK: '40000',
  SERIALIZATION_FAILURE: '40001',
  DEADLOCK_DETECTED: '40P01',
  SYNTAX_ERROR_OR_ACCESS_RULE_VIOLATION: '42000',
  SYNTAX_ERROR: '42601',
  INSUFFICIENT_PRIVILEGE: '42501',
  CANNOT_COERCE: '42846',
  GROUPING_ERROR: '42803',
  WINDOWING_ERROR: '42P20',
  INVALID_RECURSION: '42P19',
  INVALID_FOREIGN_KEY: '42830',
  INVALID_NAME: '42602',
  NAME_TOO_LONG: '42622',
  RESERVED_NAME: '42939',
  DATATYPE_MISMATCH: '42804',
  INDETERMINATE_DATATYPE: '42P18',
  COLLATION_MISMATCH: '42P21',
  INDETERMINATE_COLLATION: '42P22',
  WRONG_OBJECT_TYPE: '42809',
  GENERATED_ALWAYS: '428C9',
  UNDEFINED_COLUMN: '42703',
  UNDEFINED_FUNCTION: '42883',
  UNDEFINED_TABLE: '42P01',
  UNDEFINED_PARAMETER: '42P02',
  UNDEFINED_OBJECT: '42704',
  DUPLICATE_COLUMN: '42701',
  DUPLICATE_CURSOR: '42P03',
  DUPLICATE_DATABASE: '42P04',
  DUPLICATE_FUNCTION: '42723',
  DUPLICATE_PSTATEMENT: '42P05',
  DUPLICATE_SCHEMA: '42P06',
  DUPLICATE_TABLE: '42P07',
  DUPLICATE_ALIAS: '42712',
  DUPLICATE_OBJECT: '42710',
  AMBIGUOUS_COLUMN: '42702',
  AMBIGUOUS_FUNCTION: '42725',
  AMBIGUOUS_PARAMETER: '42P08',
  AMBIGUOUS_ALIAS: '42P09',
  INVALID_COLUMN_REFERENCE: '42P10',
  INVALID_COLUMN_DEFINITION: '42611',
  INVALID_CURSOR_DEFINITION: '42P11',
  INVALID_DATABASE_DEFINITION: '42P12',
  INVALID_FUNCTION_DEFINITION: '42P13',
  INVALID_PSTATEMENT_DEFINITION: '42P14',
  INVALID_SCHEMA_DEFINITION: '42P15',
  INVALID_TABLE_DEFINITION: '42P16',
  INVALID_OBJECT_DEFINITION: '42P17',
  WITH_CHECK_OPTION_VIOLATION: '44000',
  INSUFFICIENT_RESOURCES: '53000',
  PROGRAM_LIMIT_EXCEEDED: '54000',
  STATEMENT_TOO_COMPLEX: '54001',
  TOO_MANY_COLUMNS: '54011',
  TOO_MANY_ARGUMENTS: '54023',
  OBJECT_NOT_IN_PREREQUISITE_STATE: '55000',
  OBJECT_IN_USE: '55006',
  CANT_CHANGE_RUNTIME_PARAM: '55P02',
  LOCK_NOT_AVAILABLE: '55P03',
  QUERY_CANCELED: '57014',
  ADMIN_SHUTDOWN: '57P01',
  UNDEFINED_FILE: '58P01',
  RAISE_EXCEPTION: 'P0001',
  NO_DATA_FOUND: 'P0002',
  TOO_MANY_ROWS: 'P0003',
  ASSERT_FAILURE: 'P0004',
  INTERNAL_ERROR: 'XX000',
} as const;

export function syntaxError(message: string, position?: number): PgError {
  return new PgError(SqlState.SYNTAX_ERROR, message, position !== undefined ? { position: position + 1 } : undefined);
}

export function notSupported(what: string): PgError {
  return new PgError(SqlState.FEATURE_NOT_SUPPORTED, `in-memory engine: ${what} is not supported`);
}

export function internalError(message: string): PgError {
  return new PgError(SqlState.INTERNAL_ERROR, message);
}
