/**
 * SQL corpus of the PostgreSQL / in-memory differential test (sql-parity.test.ts).
 *
 * Every case runs in its own rolled-back transaction with a private `sql_parity` schema first on the
 * search path. Statements must be deterministic: ORDER BY whatever order the result depends on, no
 * clock or random output, and text ordering only under COLLATE "C" (the server's default collation is
 * a locale setting, not SQL semantics).
 *
 * Deliberately not covered (would test server configuration or physical storage, not SQL behaviour):
 * - text ordering / upper() / lower() under the database's default (locale) collation
 * - the money type: its text form follows the server's lc_monetary locale
 * - row order of unordered queries, ctid / xmin values, EXPLAIN costs, pg_stat_* views
 * - OIDs of objects created by the case (they depend on the server's OID counter; the test compares
 *   result column types at or above FirstNormalObjectId as "user-defined")
 * - DML on system catalogs (`DELETE FROM pg_class ...`): the in-memory catalogs are not heap tables
 */

export type ParityStatement = string | { sql: string; params: unknown[] };

export interface ParityCase {
  name: string;
  statements: ParityStatement[];
}

const p = (sql: string, ...params: unknown[]): ParityStatement => ({ sql, params });

export const sqlParityCorpus: ParityCase[] = [
  {
    name: 'literals and casts',
    statements: [
      "SELECT 1, 1.5, 'text', true, false, NULL, 2147483648, 9223372036854775808",
      "SELECT '42'::int, '42.10'::numeric, '1e3'::float8, 'yes'::boolean, 'off'::boolean",
      "SELECT 3::int2, 3::int8, 3::numeric(6,2), 3.14159::numeric(4,2), 2.5::int, (-2.5)::int, 1.5::int8",
      "SELECT '2024-02-29'::date, '2024-02-29 13:45:01.5'::timestamp, '13:45'::time, '1 day 02:00'::interval",
      "SELECT 'abc'::varchar(2), 'abc'::char(5) || '|', length('abc'::char(5)), 'a  '::char(3) = 'a'::char(3)",
      "SELECT CAST('x' AS int)",
      "SELECT '2024-13-01'::date",
      "SELECT 'maybe'::boolean",
      "SELECT 12345678901::int",
      "SELECT 70000::int2",
      "SELECT pg_typeof(1), pg_typeof(1.0), pg_typeof('a'), pg_typeof(1::int8 + 1), pg_typeof(1 + 1.0), pg_typeof(now()::date - 1)",
      "SELECT '00000000-0000-0000-0000-000000000001'::uuid, 'A0EEBC99-9C0B-4EF8-BB6D-6BB9BD380A11'::uuid",
      "SELECT 'not-a-uuid'::uuid",
      "SELECT '\\x0102ff'::bytea, 'abc'::bytea, decode('68656c6c6f', 'hex'), encode('hello'::bytea, 'base64')",
      "SELECT '{1,2,3}'::int[], '{{1,2},{3,4}}'::int[], '{a,\"b c\",NULL}'::text[]",
      "SELECT ARRAY[1,2] || 3, 'x' || 1, 1 || 'x'",
    ],
  },
  {
    name: 'integer and numeric arithmetic',
    statements: [
      'SELECT 7 / 2, -7 / 2, 7 % 3, -7 % 3, 7.0 / 2, 2 ^ 10, |/ 16, @ -5',
      'SELECT 1 / 0',
      'SELECT 1.0 / 0',
      'SELECT 1::float8 / 0',
      'SELECT 5 % 0',
      'SELECT 2147483647 + 1',
      'SELECT 2147483647::int8 + 1',
      'SELECT 9223372036854775807 + 1',
      'SELECT (-32768)::int2 * -1::int2',
      'SELECT round(2.5), round(-2.5), round(2.567, 2), round(2.5::float8), trunc(2.567, 1), ceil(-1.5), floor(-1.5)',
      'SELECT 0.1 + 0.2, 0.1::float8 + 0.2::float8, 1e-10::float8, 123456789.123456789::float8, 1/3::float4',
      "SELECT 'NaN'::numeric, 'Infinity'::float8, '-Infinity'::float8 < 0, 'NaN'::float8 = 'NaN'::float8",
      'SELECT 10::numeric / 3, 1::numeric / 7, 2::numeric ^ 0.5, sqrt(2::numeric), exp(1::numeric), ln(10::numeric)',
      'SELECT sqrt(123.456::numeric), ln(0.001::numeric), log(2::numeric, 1e20::numeric), log(1000::numeric), exp(-5::numeric), 1.5::numeric ^ 20, 99999.9999::numeric ^ -2, 0.000000012345::numeric ^ 0.333, (-2.5)::numeric ^ 3',
      'SELECT ln(0::numeric)',
      'SELECT (-8)::numeric ^ 0.5',
      'SELECT exp(10000::numeric)',
      'SELECT stddev(x), variance(x), stddev_pop(x), var_pop(x) FROM (VALUES (1.5::numeric), (2.25), (10)) v(x)',
      'SELECT stddev(x), variance(x) FROM (VALUES (1), (2), (4)) v(x)',
      'SELECT abs(-3), sign(-3.5), mod(10, 3), div(10, 3), gcd(12, 18), lcm(4, 6), factorial(10)',
      'SELECT 1.10 * 2, 1.10::numeric(10,3), scale(1.100), trim_scale(1.100), min_scale(1.100)',
      'SELECT width_bucket(5.35, 0.024, 10.06, 5), greatest(1, 3, 2), least(1.5, 0.5), greatest(1, NULL, 3)',
      'SELECT 5 & 3, 5 | 3, 5 # 3, ~5, 1 << 4, 256 >> 2',
      'SELECT sqrt(-1)',
      'SELECT ln(0)',
      "SELECT to_char(1234.5, 'FM9,999.00'), to_char(-0.5, '990.99'), to_number('1,234.50', '9,999.99')",
      'SELECT 123.456::numeric(5,2)',
      'SELECT 1234.5::numeric(5,2)',
    ],
  },
  {
    name: 'text functions and pattern matching',
    statements: [
      "SELECT length('héllo'), octet_length('héllo'), char_length('abc'), bit_length('a')",
      "SELECT substring('abcdef' from 2 for 3), substr('abcdef', -1, 3), left('abcdef', 2), right('abcdef', -2), overlay('abcdef' placing 'XY' from 3 for 2)",
      "SELECT position('cd' in 'abcdef'), strpos('abcdef', 'x'), replace('aXbXc', 'X', '-'), translate('12345', '143', 'ax'), reverse('abc')",
      "SELECT trim('  a  ') || '|', ltrim('xxaxx', 'x'), rtrim('xxaxx', 'x'), btrim('  a  '), lpad('7', 3, '0'), rpad('ab', 5, '*-'), repeat('ab', 3)",
      "SELECT split_part('a,b,c', ',', 2), split_part('a,b,c', ',', -1), string_to_array('a,b,,c', ','), array_to_string(ARRAY['a', NULL, 'c'], '-', '?')",
      "SELECT concat('a', NULL, 1), concat_ws('/', 'a', NULL, 'b'), 'a' || NULL, format('%s-%I-%L', 'x', 'my col', 'it''s'), format('%3$s %1$s', 'a', 'b', 'c')",
      "SELECT initcap('hello wORLD'), quote_ident('Table'), quote_literal('O''Reilly'), quote_nullable(NULL), md5('abc'), to_hex(255), ascii('A'), chr(66)",
      "SELECT 'abc' LIKE 'a%', 'abc' LIKE '_b_', 'ABC' ILIKE 'a%', 'a%c' LIKE 'a\\%c', 'abc' NOT LIKE '%d', 'abc' SIMILAR TO '(a|x)bc'",
      "SELECT 'abc123' ~ '[0-9]+$', 'ABC' ~* 'abc', 'abc' !~ 'x', regexp_replace('a1b22c333', '[0-9]+', '#', 'g'), regexp_match('key=val', '(\\w+)=(\\w+)')",
      "SELECT regexp_matches('a1b2c3', '[0-9]', 'g') ORDER BY 1",
      "SELECT regexp_split_to_array('a1b22c', '[0-9]+'), regexp_count('banana', 'an'), regexp_substr('abc123def', '[0-9]+'), regexp_like('Abc', 'abc', 'i')",
      "SELECT * FROM regexp_split_to_table('one two  three', '\\s+') WITH ORDINALITY",
      "SELECT starts_with('abcdef', 'abc'), 'abc' ^@ 'ab', to_ascii('abc'), convert_to('é', 'UTF8'), unistr('\\0041')",
      "SELECT string_agg(x, ',' ORDER BY x COLLATE \"C\") FROM (VALUES ('b'), ('a'), (NULL), ('c')) v(x)",
      "SELECT 'x' || repeat('y', -1), substring('abc' from 'b(.)')",
      "SELECT format('%s', 1, 2), format('%z', 1)",
      "SELECT 'abc' ~ '('",
    ],
  },
  {
    name: 'NULL semantics and conditional expressions',
    statements: [
      'SELECT NULL = NULL, NULL IS NULL, NULL IS DISTINCT FROM NULL, 1 IS DISTINCT FROM NULL, NULL AND false, NULL OR true, NOT NULL::boolean',
      'SELECT coalesce(NULL, NULL, 3), nullif(1, 1), nullif(1, 2), coalesce(NULL::int, 0) + 1',
      "SELECT CASE WHEN 1 > 2 THEN 'a' WHEN NULL THEN 'b' ELSE 'c' END, CASE 2 WHEN 1 THEN 'one' WHEN 2 THEN 'two' END, CASE WHEN false THEN 1 END",
      'SELECT 1 IN (1, NULL), 2 IN (1, NULL), 2 NOT IN (1, NULL), NULL IN (1, 2), 1 = ANY (ARRAY[1, NULL]), 2 = ALL (ARRAY[2, NULL])',
      'SELECT true IS TRUE, NULL::boolean IS NOT FALSE, NULL::boolean IS UNKNOWN, (NULL::int < 1) IS NULL',
      "SELECT CASE WHEN 1 = 1 THEN 1 ELSE 'x' END",
      'SELECT CASE WHEN true THEN 1 ELSE 1 / 0 END',
      'SELECT num_nulls(1, NULL, NULL), num_nonnulls(1, NULL, 2)',
      'SELECT count(*), count(x), sum(x), avg(x), max(x), bool_and(x > 0) FROM (VALUES (NULL::int), (NULL)) v(x)',
      'SELECT sum(x), count(*) FROM (SELECT 1 AS x WHERE false) s',
    ],
  },
  {
    name: 'date, time and interval arithmetic',
    statements: [
      "SELECT date '2024-01-31' + 1, date '2024-03-01' - date '2024-02-01', date '2024-01-31' + interval '1 month', timestamp '2024-01-31 10:00' + interval '1 month 1 day 1 hour'",
      "SELECT interval '1 day' * 3, interval '90 minutes', interval '1 year 2 months' / 2, interval '-1 day 2 hours', justify_hours(interval '27 hours'), justify_days(interval '45 days'), justify_interval(interval '1 month -1 hour')",
      "SELECT extract(year from date '2024-02-29'), extract(dow from date '2024-02-29'), extract(epoch from timestamp '2024-01-01 00:00:00'), extract(epoch from interval '1 day 1 second'), date_part('isodow', date '2024-03-03')",
      "SELECT extract(quarter from timestamp '2024-08-15'), extract(week from date '2024-12-30'), extract(isoyear from date '2024-12-30'), extract(doy from date '2024-12-31'), extract(microseconds from time '10:00:01.25')",
      "SELECT date_trunc('month', timestamp '2024-02-29 13:45:12'), date_trunc('week', timestamp '2024-02-29 13:45'), date_trunc('quarter', date '2024-05-20'), date_trunc('hour', interval '3 days 04:05:06')",
      "SELECT timestamptz '2024-03-31 01:30:00+00' AT TIME ZONE 'Europe/Bratislava', timestamp '2024-10-27 02:30' AT TIME ZONE 'Europe/Bratislava', timestamptz '2024-06-01 12:00Z' AT TIME ZONE 'America/New_York'",
      "SELECT date_trunc('day', timestamptz '2024-03-31 12:00+00', 'Europe/Bratislava'), timestamptz '2024-01-01 00:00:00+05:30', '2024-01-01 12:00 PST'::timestamptz",
      "SELECT to_char(timestamp '2024-02-29 13:05:09.123', 'YYYY-MM-DD HH24:MI:SS.MS Dy Mon DDD IW'), to_char(date '2024-07-04', 'FMDay, FMMonth DDth YYYY'), to_char(interval '15 hours 3 minutes', 'HH24:MI')",
      "SELECT to_date('29.02.2024', 'DD.MM.YYYY'), to_timestamp('2024-02-29 13:45', 'YYYY-MM-DD HH24:MI'), to_timestamp(0), make_date(2024, 2, 29), make_interval(days => 3, hours => 2)",
      "SELECT age(timestamp '2024-03-15', timestamp '2023-01-31'), age(date '2024-02-29', date '2023-02-28'), timestamp '2024-01-01' - timestamp '2023-12-25 12:00'",
      "SELECT * FROM generate_series(timestamp '2024-01-30', timestamp '2024-02-02', interval '1 day')",
      "SELECT * FROM generate_series(date '2024-01-31', date '2024-05-31', interval '1 month')",
      "SELECT (date '2024-01-01', date '2024-02-01') OVERLAPS (date '2024-01-15', date '2024-03-01'), date '2024-01-01' BETWEEN date '2023-12-31' AND date '2024-01-02'",
      "SELECT 'infinity'::date > '2999-01-01', '-infinity'::timestamp, isfinite(date 'infinity'), 'epoch'::timestamp, 'allballs'::time",
      "SELECT date '2024-02-30'",
      "SELECT timestamp '2024-01-01' + 1",
      "SELECT interval '1 day' + date '2024-01-01', time '23:30' + interval '1 hour', date '2024-01-01' + time '10:00', timetz '10:00+02'",
      "SELECT timestamp '294277-01-01'",
      "SELECT to_char(timestamptz '2024-06-01 12:00Z', 'YYYY-MM-DD HH24:MI TZ OF')",
      "SELECT extract(timezone_hour from timestamptz '2024-06-01 12:00+00'), EXTRACT(century FROM date '2000-12-31'), EXTRACT(millennium FROM date '2001-01-01')",
    ],
  },
  {
    name: 'arrays',
    statements: [
      "SELECT ARRAY[1,2,3][2]",
      "SELECT (ARRAY[1,2,3])[2], (ARRAY[1,2,3])[2:3], (ARRAY[1,2,3])[:2], (ARRAY[[1,2],[3,4]])[2][1], (ARRAY[[1,2],[3,4]])[1:1], (ARRAY[1,2,3])[5], ('{1,2,3}'::int[])[0]",
      'SELECT array_length(ARRAY[1,2,3], 1), cardinality(ARRAY[[1,2],[3,4]]), array_dims(ARRAY[[1,2],[3,4]]), array_lower(ARRAY[1], 1), array_upper(ARRAY[]::int[], 1), array_ndims(ARRAY[[1]])',
      'SELECT array_append(ARRAY[1], 2), array_prepend(0, ARRAY[1]), array_cat(ARRAY[1], ARRAY[2,3]), array_remove(ARRAY[1,2,1], 1), array_replace(ARRAY[1,2,1], 1, 9), array_position(ARRAY[5,6,7], 6), array_positions(ARRAY[1,2,1], 1)',
      'SELECT ARRAY[1,2] @> ARRAY[2], ARRAY[1,2] <@ ARRAY[1,2,3], ARRAY[1,2] && ARRAY[2,5], ARRAY[1,2] = ARRAY[1,2], ARRAY[1,2] < ARRAY[1,3], ARRAY[1,NULL] = ARRAY[1,NULL]',
      'SELECT 3 = ANY (ARRAY[1,2,3]), 3 > ALL (ARRAY[1,2]), 1 = ANY (ARRAY[]::int[]), 1 = ALL (ARRAY[]::int[]), NULL = ANY (ARRAY[1])',
      "SELECT * FROM unnest(ARRAY['a','b','c']) WITH ORDINALITY AS u(v, n)",
      "SELECT * FROM unnest(ARRAY[1,2], ARRAY['x','y','z']) AS u(a, b)",
      'SELECT unnest(ARRAY[[1,2],[3,4]])',
      'SELECT array_agg(x ORDER BY x DESC), array_agg(DISTINCT x ORDER BY x) FROM (VALUES (1), (3), (2), (3)) v(x)',
      'SELECT array_agg(a) FROM (VALUES (ARRAY[1,2]), (ARRAY[3,4])) v(a)',
      'SELECT array_agg(a) FROM (VALUES (ARRAY[1,2]), (ARRAY[3])) v(a)',
      "SELECT ARRAY(SELECT generate_series(1, 3)), array_fill(7, ARRAY[2, 2]), string_to_array('1 2 3', ' ')::int[], trim_array(ARRAY[1,2,3], 1), array_sample(ARRAY[1], 1)",
      "SELECT '[0:2]={1,2,3}'::int[], ('[0:2]={1,2,3}'::int[])[0], array_to_string('{1,2}'::int[], ','), '{}'::text[] = ARRAY[]::text[]",
      'SELECT ARRAY[1, 2] || ARRAY[[3, 4]]',
      "SELECT ARRAY['a'] || 'b'::text, ARRAY[1.5, 2]::int[], ARRAY['1', 'x']::int[]",
      'SELECT array_reverse(ARRAY[1,2,3]), array_sort(ARRAY[3,1,2])',
    ],
  },
  {
    name: 'json and jsonb',
    statements: [
      `SELECT '{"a": 1, "b": [1, 2, {"c": "x"}]}'::jsonb -> 'b' -> 2 ->> 'c', '{"a": 1}'::json -> 'a', '[1,2,3]'::jsonb -> -1, '{"a": {"b": 2}}'::jsonb #> '{a,b}', '{"a": {"b": 2}}'::jsonb #>> '{a,b}'`,
      `SELECT '{"b": 1, "a": 2, "a": 3}'::jsonb, '{"b": 1, "a": 2, "a": 3}'::json, '[1, 2.50, 1e2, true, null, "s"]'::jsonb, ' { "x" : 1 } '::json`,
      `SELECT '{"a": 1, "b": 2}'::jsonb @> '{"a": 1}', '{"a": 1}'::jsonb <@ '{"a": 1, "b": 2}', '{"a": 1}'::jsonb ? 'a', '{"a": 1, "b": 2}'::jsonb ?| ARRAY['x', 'b'], '["a", "b"]'::jsonb ?& ARRAY['a', 'b']`,
      `SELECT '{"a": 1}'::jsonb || '{"b": 2}', '{"a": 1, "b": 2}'::jsonb - 'a', '[1, 2, 3]'::jsonb - 1, '{"a": {"b": 1, "c": 2}}'::jsonb #- '{a,b}'`,
      `SELECT jsonb_set('{"a": {"b": 1}}', '{a,c}', '"new"'), jsonb_set('[1,2]', '{5}', '9'), jsonb_insert('{"a": [1, 2]}', '{a,1}', '7'), jsonb_set_lax('{"a": 1}', '{a}', NULL)`,
      `SELECT jsonb_build_object('a', 1, 'b', ARRAY[1, 2], 'c', NULL, 'd', now()::date - now()::date), json_build_array(1, 'x', true, NULL), jsonb_build_object('k', 1.50::numeric, 'ts', timestamp '2024-01-01 10:00')`,
      `SELECT json_agg(x ORDER BY x), jsonb_agg(x ORDER BY x DESC), json_object_agg(k, v ORDER BY k), jsonb_object_agg(k, v) FROM (VALUES (1, 'a', 10), (2, 'b', 20)) t(x, k, v)`,
      `SELECT row_to_json(r), to_jsonb(r), to_json('text'::text), to_jsonb(ARRAY[1, 2]) FROM (SELECT 1 AS id, 'x' AS name, NULL::int AS empty) r`,
      `SELECT * FROM jsonb_each('{"b": 2, "a": {"x": 1}}') ORDER BY key COLLATE "C"`,
      `SELECT * FROM jsonb_each_text('{"b": 2, "a": null}') ORDER BY key COLLATE "C"`,
      `SELECT * FROM jsonb_array_elements('[1, "two", {"three": 3}]') WITH ORDINALITY`,
      `SELECT * FROM jsonb_to_record('{"a": 1, "b": "x", "c": [1,2]}') AS r(a int, b text, c int[])`,
      `SELECT * FROM jsonb_to_recordset('[{"a": 1}, {"a": 2, "b": true}]') AS r(a int, b boolean)`,
      `SELECT * FROM jsonb_to_record('[1]') AS r(a int)`,
      `SELECT * FROM jsonb_to_record('{"c": 5}') AS r(c int[])`,
      // json(b)_populate_record(set): the row type comes from the (usually NULL) first argument
      `CREATE TABLE jpr (id int, name text, price numeric(8,2), flag bool, at timestamp, tags text[], meta jsonb)`,
      `INSERT INTO jpr VALUES (1, 'a', 2.50, true, '2024-01-02 03:04:05', '{x,y}', '{"k": [1]}')`,
      `INSERT INTO jpr SELECT (jsonb_populate_record(NULL::jpr, to_jsonb(p) || jsonb_build_object('id', 2, 'name', 'b'))).* FROM jpr p WHERE p.id = 1`,
      `INSERT INTO jpr SELECT * FROM jsonb_populate_record(NULL::jpr, '{"id": 3, "name": "c", "price": 9, "flag": "false", "at": "2020-06-07T08:09:10", "tags": ["p","q"], "meta": {"z": 1}}'::jsonb)`,
      `SELECT * FROM jpr ORDER BY id`,
      `SELECT (jsonb_populate_record(ROW(9, 'base', 1.25, true, NULL, NULL, NULL)::jpr, '{"name": "over", "price": null}'::jsonb)).*`,
      `SELECT * FROM jsonb_populate_record(NULL::jpr, NULL::jsonb)`,
      `SELECT * FROM json_populate_record(NULL::jpr, '{"id": 4, "nosuchcolumn": 1, "NAME": "wrong", "name": "right"}'::json)`,
      `SELECT * FROM jsonb_populate_recordset(NULL::jpr, '[{"id": 1}, {"id": 2, "name": "s"}]'::jsonb) ORDER BY id`,
      `SELECT * FROM jsonb_populate_record(NULL::record, '{"a": 1, "b": "x"}'::jsonb) AS r(a int, b text)`,
      `SELECT jsonb_populate_record_valid(NULL::jpr, '{"id": 1}'), jsonb_populate_record_valid(NULL::jpr, '{"id": "zz"}'), jsonb_populate_record_valid(NULL::jpr, NULL), pg_typeof(jsonb_populate_record(NULL::jpr, '{}'))`,
      `SELECT * FROM jsonb_populate_record(NULL::jpr, '[1]'::jsonb)`,
      `SELECT * FROM jsonb_populate_recordset(NULL::jpr, '{"id": 1}'::jsonb)`,
      `SELECT jsonb_populate_record(NULL::int, '{}'::jsonb)`,
      `SELECT jsonb_populate_record(NULL::record, '{"a": 1}'::jsonb)`,
      `SELECT * FROM jsonb_populate_record(NULL::jpr, '{"tags": 5}'::jsonb)`,
      `SELECT jsonb_typeof('1'), jsonb_typeof('"s"'), jsonb_array_length('[1,2]'), jsonb_object_keys('{"x":1}'), jsonb_strip_nulls('{"a": null, "b": [null]}'), jsonb_pretty('{"a": [1, {"b": 2}]}')`,
      `SELECT jsonb_path_query_array('{"items": [{"p": 5}, {"p": 15}, {"p": 25}]}', '$.items[*] ? (@.p > 10).p'), jsonb_path_exists('{"a": [1, 2]}', '$.a[*] ? (@ == 2)'), '{"a": 1}'::jsonb @? '$.a', '{"a": 5}'::jsonb @@ '$.a > 3'`,
      `SELECT * FROM jsonb_path_query('{"a": [1, 2, 3]}', '$.a[*] ? (@ >= $min)', '{"min": 2}')`,
      `SELECT '{"a": 1'::jsonb`,
      `SELECT '{"a": "x"}'::jsonb -> 'a' = '"x"', ('{"n": 12}'::jsonb ->> 'n')::int + 1, '{"a": 1}'::jsonb = '{ "a" : 1 }', '[1,2]'::jsonb < '[1,3]'`,
      `SELECT json_typeof('{"a": 1}'::json -> 'a'), '{"a": [1,2]}'::json #>> '{a,1}', json_array_length('[1,2,3]'), json_strip_nulls('{"a": null}')`,
      `SELECT JSON_VALUE('{"a": {"b": 42}}', '$.a.b' RETURNING int), JSON_QUERY('{"a": [1,2]}', '$.a'), JSON_EXISTS('{"a": 1}', '$.b'), '{"a":1}' IS JSON OBJECT`,
      `SELECT ('{"a": 1}'::jsonb)['a'], ('{"a": {"b": [10, 20]}}'::jsonb)['a']['b'][1]`,
      // jsonb keeps a top-level scalar as a one-element array, so -> / ->> with 0 or -1 reach it ...
      `SELECT '5'::jsonb -> 0, '5'::jsonb -> -1, '"s"'::jsonb ->> 0, 'true'::jsonb ->> 0, to_jsonb(true) ->> 0, 'null'::jsonb ->> 0, 'null'::jsonb -> 0`,
      `SELECT '5'::jsonb -> 1, '5'::jsonb -> -2, '5'::jsonb -> 'a', '{"a":1}'::jsonb -> 0, '[10,20]'::jsonb -> -1, '[10,20]'::jsonb -> 5`,
      // ... and nothing else does: not #>, not the [ ] subscript, not the json (text) type
      `SELECT '5'::jsonb #> '{0}', '5'::jsonb #>> '{0}', '5'::jsonb #> '{}', ('5'::jsonb)[0], '5'::json -> 0, '5'::json ->> 0`,
    ],
  },
  {
    name: 'aggregates',
    statements: [
      'CREATE TABLE sales (id int PRIMARY KEY, region text, product text, qty int, price numeric(10,2), sold_on date)',
      `INSERT INTO sales VALUES
        (1, 'east', 'apple', 10, 1.20, '2024-01-05'), (2, 'east', 'pear', 5, 2.00, '2024-01-06'), (3, 'west', 'apple', 7, 1.10, '2024-02-01'),
        (4, 'west', 'plum', NULL, 3.00, '2024-02-03'), (5, 'north', 'apple', 3, 1.25, '2024-02-10'), (6, 'east', 'apple', 2, 1.30, '2024-03-01')`,
      'SELECT count(*), count(qty), sum(qty), avg(qty), min(price), max(sold_on), sum(qty * price), avg(price)::numeric(10,4) FROM sales',
      'SELECT region, count(*) AS n, sum(qty) AS total FROM sales GROUP BY region ORDER BY region COLLATE "C"',
      'SELECT region, sum(qty) FROM sales GROUP BY region HAVING sum(qty) > 9 ORDER BY region COLLATE "C"',
      'SELECT region FROM sales GROUP BY region ORDER BY 1 COLLATE "C"',
      "SELECT count(*) FILTER (WHERE product = 'apple'), sum(qty) FILTER (WHERE region <> 'east'), count(DISTINCT product), string_agg(DISTINCT product, ',' ORDER BY product COLLATE \"C\") FROM sales",
      'SELECT stddev(qty)::numeric(10,6), variance(qty)::numeric(10,6), stddev_pop(price)::numeric(10,6), corr(qty, price)::numeric(10,6), regr_slope(qty, price)::numeric(10,6) FROM sales',
      "SELECT bool_and(qty > 2), bool_or(qty > 9), every(price > 1), bit_and(qty), bit_or(qty), percentile_cont(0.5) WITHIN GROUP (ORDER BY qty), percentile_disc(0.5) WITHIN GROUP (ORDER BY qty), mode() WITHIN GROUP (ORDER BY product COLLATE \"C\") FROM sales",
      'SELECT region, product, sum(qty) FROM sales GROUP BY GROUPING SETS ((region), (product), ()) ORDER BY region COLLATE "C" NULLS LAST, product COLLATE "C" NULLS LAST',
      'SELECT region, product, sum(qty), grouping(region, product) FROM sales GROUP BY ROLLUP (region, product) ORDER BY region COLLATE "C" NULLS LAST, product COLLATE "C" NULLS LAST',
      'SELECT region, product, count(*) FROM sales GROUP BY CUBE (region, product) ORDER BY region COLLATE "C" NULLS FIRST, product COLLATE "C" NULLS FIRST',
      "SELECT date_trunc('month', sold_on) AS m, count(*) FROM sales GROUP BY 1 ORDER BY 1",
      'SELECT region, qty FROM sales GROUP BY region',
      'SELECT sum(qty) FROM sales WHERE sum(qty) > 1',
      'SELECT max(count(*)) FROM sales',
      "SELECT sum('x')",
      'SELECT avg(x) FROM (VALUES (1), (2)) v(x)',
      'SELECT sum(x), avg(x) FROM (VALUES (1.5::float8), (2.25)) v(x)',
      'SELECT sum(x) FROM (VALUES (9223372036854775807), (1)) v(x)',
      'SELECT count(*) OVER (), region FROM sales GROUP BY region ORDER BY region COLLATE "C"',
      'SELECT any_value(region) IS NOT NULL, min(region COLLATE "C"), max(product COLLATE "C") FROM sales',
    ],
  },
  {
    name: 'window functions',
    statements: [
      'CREATE TABLE scores (player text, game int, points int)',
      "INSERT INTO scores VALUES ('ann', 1, 10), ('ann', 2, 30), ('ann', 3, 20), ('bob', 1, 30), ('bob', 2, 30), ('bob', 3, 5), ('cid', 1, 15)",
      'SELECT player, game, points, row_number() OVER w, rank() OVER w, dense_rank() OVER w, percent_rank() OVER w, cume_dist() OVER w FROM scores WINDOW w AS (ORDER BY points DESC) ORDER BY points DESC, player COLLATE "C", game',
      'SELECT player, game, sum(points) OVER (PARTITION BY player ORDER BY game) AS running, avg(points) OVER (PARTITION BY player) AS mean FROM scores ORDER BY player COLLATE "C", game',
      'SELECT player, game, lag(points) OVER p, lead(points, 1, -1) OVER p, first_value(points) OVER p, last_value(points) OVER p, nth_value(points, 2) OVER p FROM scores WINDOW p AS (PARTITION BY player ORDER BY game) ORDER BY player COLLATE "C", game',
      'SELECT game, points, sum(points) OVER (ORDER BY game, player COLLATE "C" ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM scores ORDER BY game, player COLLATE "C"',
      'SELECT game, points, sum(points) OVER (ORDER BY game RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), count(*) OVER (ORDER BY points GROUPS BETWEEN 1 PRECEDING AND CURRENT ROW) FROM scores ORDER BY game, points, player COLLATE "C"',
      'SELECT points, sum(points) OVER (ORDER BY points RANGE BETWEEN 10 PRECEDING AND 5 FOLLOWING EXCLUDE CURRENT ROW) FROM scores ORDER BY points, player COLLATE "C", game',
      'SELECT player, ntile(2) OVER (ORDER BY player COLLATE "C", game), count(*) FILTER (WHERE points > 10) OVER (PARTITION BY player) FROM scores ORDER BY player COLLATE "C", game',
      'SELECT * FROM (SELECT player, game, points, rank() OVER (PARTITION BY player ORDER BY points DESC) AS r FROM scores) s WHERE r = 1 ORDER BY player COLLATE "C", game',
      'SELECT player, row_number() OVER (PARTITION BY player ORDER BY game) FROM scores WHERE row_number() OVER () > 1',
      'SELECT sum(sum(points)) OVER (), player FROM scores GROUP BY player ORDER BY player COLLATE "C"',
      'SELECT ntile(0) OVER () FROM scores',
    ],
  },
  {
    name: 'joins',
    statements: [
      'CREATE TABLE dept (id int PRIMARY KEY, name text)',
      'CREATE TABLE emp (id int PRIMARY KEY, name text, dept_id int, manager_id int, salary int)',
      "INSERT INTO dept VALUES (1, 'eng'), (2, 'ops'), (3, 'empty')",
      "INSERT INTO emp VALUES (1, 'ada', 1, NULL, 300), (2, 'bo', 1, 1, 200), (3, 'cy', 2, 1, 150), (4, 'di', NULL, 2, 100), (5, 'ed', 9, 3, 120)",
      'SELECT e.name, d.name FROM emp e JOIN dept d ON d.id = e.dept_id ORDER BY e.id',
      'SELECT e.name, d.name FROM emp e LEFT JOIN dept d ON d.id = e.dept_id ORDER BY e.id',
      'SELECT e.name, d.name FROM emp e RIGHT JOIN dept d ON d.id = e.dept_id ORDER BY d.id, e.id',
      'SELECT e.name, d.name FROM emp e FULL JOIN dept d ON d.id = e.dept_id ORDER BY d.id NULLS FIRST, e.id NULLS FIRST',
      'SELECT count(*) FROM emp CROSS JOIN dept',
      'SELECT e.name, m.name AS manager FROM emp e LEFT JOIN emp m ON m.id = e.manager_id ORDER BY e.id',
      'SELECT d.name, top.name, top.salary FROM dept d CROSS JOIN LATERAL (SELECT name, salary FROM emp WHERE dept_id = d.id ORDER BY salary DESC LIMIT 1) top ORDER BY d.id',
      'SELECT d.name, x.cnt FROM dept d LEFT JOIN LATERAL (SELECT count(*) AS cnt FROM emp WHERE dept_id = d.id) x ON true ORDER BY d.id',
      'CREATE TABLE a1 (k int, va text)',
      'CREATE TABLE b1 (k int, vb text)',
      "INSERT INTO a1 VALUES (1, 'a'), (2, 'b'), (NULL, 'n')",
      "INSERT INTO b1 VALUES (1, 'x'), (1, 'y'), (NULL, 'm')",
      'SELECT * FROM a1 JOIN b1 USING (k) ORDER BY vb COLLATE "C"',
      'SELECT * FROM a1 NATURAL LEFT JOIN b1 ORDER BY va COLLATE "C", vb COLLATE "C"',
      'SELECT * FROM a1 FULL JOIN b1 USING (k) ORDER BY k NULLS LAST, va COLLATE "C" NULLS LAST, vb COLLATE "C" NULLS LAST',
      'SELECT a1.k, b1.k FROM a1 JOIN b1 ON a1.k IS NOT DISTINCT FROM b1.k ORDER BY 1 NULLS LAST, b1.vb COLLATE "C"',
      'SELECT * FROM a1 JOIN b1 ON a1.k = b1.k AND b1.vb = \'y\'',
      'SELECT * FROM a1 LEFT JOIN b1 ON a1.k = b1.k WHERE b1.k IS NULL ORDER BY va COLLATE "C"',
      'SELECT k FROM a1 JOIN b1 USING (k) JOIN emp ON emp.id = k',
      'SELECT name FROM emp JOIN dept ON dept.id = emp.dept_id',
      'SELECT * FROM emp e JOIN dept d',
      'SELECT e.name FROM emp e, LATERAL (SELECT e.salary * 2 AS double) x WHERE x.double > 400',
      // a function in FROM whose arguments read a preceding FROM item is IMPLICITLY lateral
      'CREATE TABLE lat (id int PRIMARY KEY, a int, b int, arr int[], j jsonb)',
      `INSERT INTO lat VALUES (1, 10, 11, '{1,2}', '[100,200]'), (2, 20, 21, '{3}', '[300]'), (3, 30, 31, '{}', '[]')`,
      'SELECT l.id, u FROM lat l, unnest(l.arr) u ORDER BY l.id, u',
      'SELECT l.id, u FROM lat l, unnest(ARRAY[l.a, l.b]) u ORDER BY l.id, u',
      'SELECT l.id, g FROM lat l, generate_series(l.a, l.b) g ORDER BY l.id, g',
      `SELECT l.id, e FROM lat l, jsonb_array_elements(l.j) e ORDER BY l.id, e::text`,
      'SELECT l.id, u.v, u.o FROM lat l, unnest(l.arr) WITH ORDINALITY AS u(v, o) ORDER BY l.id, u.o',
      'SELECT l.id, x, y FROM lat l, ROWS FROM (generate_series(1, 2), unnest(l.arr)) AS r(x, y) ORDER BY l.id, x, y NULLS LAST',
      'SELECT l.id, a.v, b.w FROM lat l, unnest(l.arr) a(v), generate_series(1, a.v) b(w) ORDER BY l.id, a.v, b.w',
      'SELECT l.id, u FROM lat l LEFT JOIN LATERAL unnest(l.arr) u ON true ORDER BY l.id, u NULLS LAST',
      // ... and a function with no outer reference stays NON-lateral: its argument is evaluated once
      // for the whole scan, which the sequence counts (3 outer rows, one nextval)
      'CREATE SEQUENCE lat_s',
      `SELECT l.id, g FROM lat l, generate_series(1, nextval('lat_s')::int) g ORDER BY l.id, g`,
      'SELECT last_value, is_called FROM lat_s',
      'SELECT l.id, u FROM lat l, unnest(ARRAY[5, 6]) u ORDER BY l.id, u',
      'SELECT g, l.id FROM generate_series(1, 2) g, lat l ORDER BY g, l.id',
      // an implicitly-lateral SRF INSIDE a correlated collection lateral: losing the correlation made
      // the whole collection come back empty, which reads as missing DATA, not as an error. The count
      // and the distinct ids are both pinned — asserting only "not empty" would not have caught it.
      'CREATE TABLE latc (id int PRIMARY KEY, parent int, opts jsonb)',
      `INSERT INTO latc VALUES (101, 1, '["x"]'), (102, 1, '["x"]'), (103, 1, '["x"]'), (104, 1, '["x"]'), (201, 2, '[]')`,
      `SELECT l.id, agg.n, agg.ids FROM lat l
         LEFT JOIN LATERAL (SELECT count(*) AS n, array_agg(DISTINCT c.id ORDER BY c.id) AS ids
                            FROM latc c, jsonb_array_elements(c.opts) o WHERE c.parent = l.id) agg ON true
       ORDER BY l.id`,
      `SELECT l.id, (SELECT count(*) FROM latc c, jsonb_array_elements(c.opts) o WHERE c.parent = l.id) AS n FROM lat l ORDER BY l.id`,
      `SELECT l.id, (SELECT json_agg(o ORDER BY c.id) FROM latc c, jsonb_array_elements(c.opts) o WHERE c.parent = l.id) AS items FROM lat l ORDER BY l.id`,
    ],
  },
  {
    name: 'subqueries',
    statements: [
      'CREATE TABLE parent_t (id int PRIMARY KEY, label text)',
      'CREATE TABLE child_t (id int PRIMARY KEY, parent_id int, amount int)',
      "INSERT INTO parent_t VALUES (1, 'one'), (2, 'two'), (3, 'three')",
      'INSERT INTO child_t VALUES (10, 1, 5), (11, 1, 7), (12, 2, 1), (13, NULL, 9)',
      'SELECT id FROM parent_t WHERE id IN (SELECT parent_id FROM child_t) ORDER BY id',
      'SELECT id FROM parent_t WHERE id NOT IN (SELECT parent_id FROM child_t) ORDER BY id',
      'SELECT id FROM parent_t WHERE id NOT IN (SELECT parent_id FROM child_t WHERE parent_id IS NOT NULL) ORDER BY id',
      'SELECT id FROM parent_t p WHERE EXISTS (SELECT 1 FROM child_t c WHERE c.parent_id = p.id AND c.amount > 6) ORDER BY id',
      'SELECT id FROM parent_t p WHERE NOT EXISTS (SELECT FROM child_t c WHERE c.parent_id = p.id) ORDER BY id',
      'SELECT p.id, (SELECT sum(amount) FROM child_t c WHERE c.parent_id = p.id) AS total, (SELECT max(amount) FROM child_t) AS overall FROM parent_t p ORDER BY p.id',
      'SELECT id FROM parent_t WHERE id > ALL (SELECT parent_id FROM child_t WHERE parent_id IS NOT NULL) ORDER BY id',
      'SELECT id FROM parent_t WHERE id = ANY (SELECT parent_id FROM child_t) ORDER BY id',
      'SELECT id FROM parent_t WHERE id > ALL (SELECT parent_id FROM child_t)',
      'SELECT (SELECT id FROM child_t)',
      'SELECT (SELECT id, amount FROM child_t LIMIT 1)',
      'SELECT (SELECT 1 WHERE false) IS NULL, ARRAY(SELECT id FROM child_t ORDER BY id DESC), (1, 2) = (SELECT 1, 2), (1, 3) > (1, 2)',
      'SELECT * FROM (SELECT parent_id, count(*) AS n FROM child_t GROUP BY parent_id) s ORDER BY parent_id NULLS FIRST',
      'SELECT p.label FROM parent_t p WHERE (SELECT count(*) FROM child_t c WHERE c.parent_id = p.id) = 2',
      'SELECT id FROM parent_t WHERE (id, label) IN (SELECT 1, \'one\' UNION SELECT 2, \'x\')',
      'SELECT * FROM (SELECT 1)',
      'SELECT x FROM (SELECT 1 AS x) AS s(y)',
    ],
  },
  {
    name: 'set operations and VALUES',
    statements: [
      'SELECT 1 UNION SELECT 1 UNION ALL SELECT 2 ORDER BY 1',
      'SELECT x FROM (VALUES (1), (2), (2), (3)) v(x) INTERSECT SELECT x FROM (VALUES (2), (2), (4)) w(x)',
      'SELECT x FROM (VALUES (1), (2), (2), (3)) v(x) INTERSECT ALL SELECT x FROM (VALUES (2), (2), (4)) w(x) ORDER BY 1',
      'SELECT x FROM (VALUES (1), (2), (2), (3)) v(x) EXCEPT ALL SELECT 2 ORDER BY 1',
      'SELECT x FROM (VALUES (1), (2), (2), (3)) v(x) EXCEPT SELECT 2 ORDER BY 1',
      "SELECT 1 AS a, 'x' UNION SELECT 2, 'y' ORDER BY a DESC LIMIT 1",
      "SELECT 1 UNION SELECT 'a'",
      'SELECT 1, 2 UNION SELECT 1',
      'SELECT NULL UNION SELECT 1 ORDER BY 1',
      'SELECT 1.5 UNION SELECT 2 ORDER BY 1',
      "VALUES (1, 'a'), (2, NULL) ORDER BY 1 DESC",
      'SELECT * FROM (VALUES (1, 2.5), (2, 3)) AS t(a, b) WHERE a > 1',
      "(SELECT 1 AS n ORDER BY 1 LIMIT 1) UNION ALL (SELECT 2 ORDER BY 1 LIMIT 1) ORDER BY n DESC",
      "SELECT * FROM (VALUES (1), ('x')) v(a)",
    ],
  },
  {
    name: 'common table expressions',
    statements: [
      'WITH t AS (SELECT 1 AS x UNION ALL SELECT 2) SELECT sum(x) FROM t',
      'WITH RECURSIVE r(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM r WHERE n < 5) SELECT array_agg(n ORDER BY n) FROM r',
      "WITH RECURSIVE fib(a, b, i) AS (SELECT 0::numeric, 1::numeric, 1 UNION ALL SELECT b, a + b, i + 1 FROM fib WHERE i < 50) SELECT a FROM fib ORDER BY i DESC LIMIT 1",
      'CREATE TABLE node (id int PRIMARY KEY, parent int, name text)',
      "INSERT INTO node VALUES (1, NULL, 'root'), (2, 1, 'a'), (3, 1, 'b'), (4, 2, 'a1'), (5, 4, 'a1x')",
      "WITH RECURSIVE tree AS (SELECT id, name, 0 AS depth, ARRAY[id] AS path FROM node WHERE parent IS NULL UNION ALL SELECT n.id, n.name, t.depth + 1, t.path || n.id FROM node n JOIN tree t ON n.parent = t.id) SELECT * FROM tree ORDER BY path",
      "WITH RECURSIVE tree AS (SELECT id, parent FROM node WHERE id = 5 UNION SELECT n.id, n.parent FROM node n JOIN tree t ON n.id = t.parent) SEARCH DEPTH FIRST BY id SET ord SELECT id FROM tree ORDER BY ord",
      'WITH RECURSIVE c(n) AS (SELECT 1 UNION ALL SELECT n FROM c) CYCLE n SET is_cycle USING path SELECT n, is_cycle FROM c',
      'WITH m AS MATERIALIZED (SELECT id FROM node), nm AS NOT MATERIALIZED (SELECT id FROM m WHERE id > 3) SELECT * FROM nm ORDER BY id',
      "WITH ins AS (INSERT INTO node VALUES (6, 5, 'new') RETURNING id, name) SELECT * FROM ins",
      "WITH del AS (DELETE FROM node WHERE id = 6 RETURNING *), upd AS (UPDATE node SET name = name || '!' WHERE id = 5 RETURNING id, name) SELECT (SELECT count(*) FROM del), (SELECT name FROM upd)",
      "WITH moved AS (DELETE FROM node WHERE parent = 4 RETURNING id, name) INSERT INTO node SELECT id + 100, 1, name FROM moved RETURNING id, parent",
      'SELECT id, parent, name FROM node ORDER BY id',
      'WITH RECURSIVE bad(n) AS (SELECT 1 UNION ALL SELECT count(*) FROM bad) SELECT * FROM bad',
      'WITH x AS (SELECT 1) SELECT * FROM y',
    ],
  },
  {
    name: 'insert, update, delete with RETURNING',
    statements: [
      "CREATE TABLE item (id serial PRIMARY KEY, sku text UNIQUE NOT NULL, qty int NOT NULL DEFAULT 0 CHECK (qty >= 0), note text, updated timestamp DEFAULT '2000-01-01')",
      "INSERT INTO item (sku) VALUES ('a') RETURNING *",
      "INSERT INTO item (sku, qty, note) VALUES ('b', 5, 'five'), ('c', 7, NULL) RETURNING id, sku, qty * 2 AS doubled",
      "INSERT INTO item (sku, qty) SELECT 'd' || g, g FROM generate_series(1, 3) g RETURNING id",
      "INSERT INTO item VALUES (DEFAULT, 'e', DEFAULT, DEFAULT, DEFAULT) RETURNING qty, note, updated",
      "UPDATE item SET qty = qty + 1, note = coalesce(note, 'none') WHERE qty < 6 RETURNING id, qty, note",
      "UPDATE item SET qty = qty - 10 WHERE sku = 'b'",
      "UPDATE item i SET note = i.note || '-' || s.sku FROM item s WHERE s.id = i.id - 1 AND i.sku = 'c' RETURNING i.id, i.note",
      "UPDATE item SET (qty, note) = (SELECT 42, 'row') WHERE sku = 'a' RETURNING qty, note",
      "UPDATE item SET qty = 1 WHERE sku = 'nope' RETURNING *",
      "DELETE FROM item WHERE sku LIKE 'd%' RETURNING sku",
      "DELETE FROM item USING item other WHERE other.sku = 'e' AND item.id = other.id RETURNING item.sku",
      'SELECT id, sku, qty, note FROM item ORDER BY id',
      "INSERT INTO item (sku) VALUES ('a')",
      'INSERT INTO item (sku) VALUES (NULL)',
      "INSERT INTO item (sku, qty) VALUES ('z', -1)",
      "INSERT INTO item (sku, missing) VALUES ('z', 1)",
      "INSERT INTO item (id, sku) VALUES ('x', 'z')",
      "INSERT INTO item (sku) VALUES ('p', 'q')",
      'UPDATE item SET qty = NULL',
      "INSERT INTO item (sku, qty) VALUES ('old', 1) RETURNING OLD.qty, NEW.qty",
      "UPDATE item SET qty = 99 WHERE sku = 'old' RETURNING old.qty AS before, new.qty AS after",
      "DELETE FROM item WHERE sku = 'old' RETURNING old.sku, new.sku",
      "SELECT currval('item_id_seq'), nextval('item_id_seq')",
    ],
  },
  {
    name: 'ON CONFLICT and MERGE',
    statements: [
      'CREATE TABLE stock (sku text PRIMARY KEY, qty int NOT NULL, note text)',
      "INSERT INTO stock VALUES ('a', 1, NULL), ('b', 2, 'x')",
      "INSERT INTO stock VALUES ('a', 10, 'dup') ON CONFLICT DO NOTHING RETURNING *",
      "INSERT INTO stock VALUES ('a', 10, 'dup'), ('c', 3, 'new') ON CONFLICT (sku) DO UPDATE SET qty = stock.qty + EXCLUDED.qty, note = EXCLUDED.note RETURNING sku, qty, note",
      "INSERT INTO stock VALUES ('b', 5, NULL) ON CONFLICT (sku) DO UPDATE SET qty = EXCLUDED.qty WHERE stock.note IS NULL RETURNING *",
      "INSERT INTO stock VALUES ('d', 1, NULL), ('d', 2, NULL) ON CONFLICT (sku) DO UPDATE SET qty = EXCLUDED.qty",
      "INSERT INTO stock VALUES ('e', 1, NULL) ON CONFLICT (qty) DO NOTHING",
      "INSERT INTO stock AS s VALUES ('a', 1, NULL) ON CONFLICT ON CONSTRAINT stock_pkey DO UPDATE SET qty = s.qty * 2 RETURNING qty",
      'CREATE TABLE incoming (sku text, qty int)',
      "INSERT INTO incoming VALUES ('a', 0), ('b', 7), ('z', 9)",
      "MERGE INTO stock s USING incoming i ON s.sku = i.sku WHEN MATCHED AND i.qty = 0 THEN DELETE WHEN MATCHED THEN UPDATE SET qty = s.qty + i.qty WHEN NOT MATCHED THEN INSERT VALUES (i.sku, i.qty, 'merged')",
      'SELECT * FROM stock ORDER BY sku COLLATE "C"',
      // RETURNING rows come out in join order, which is plan-dependent: order them
      "WITH m AS (MERGE INTO stock s USING (VALUES ('b', 1), ('y', 2)) v(sku, qty) ON s.sku = v.sku WHEN MATCHED THEN UPDATE SET note = 'm' WHEN NOT MATCHED BY SOURCE AND s.sku = 'c' THEN DELETE WHEN NOT MATCHED THEN DO NOTHING RETURNING merge_action(), s.sku, old.note AS old_note) SELECT * FROM m ORDER BY sku COLLATE \"C\"",
      'SELECT merge_action()',
      "MERGE INTO stock s USING (VALUES ('b'), ('b')) v(sku) ON s.sku = v.sku WHEN MATCHED THEN UPDATE SET qty = 0",
      'SELECT * FROM stock ORDER BY sku COLLATE "C"',
    ],
  },
  {
    name: 'constraints and foreign keys',
    statements: [
      'CREATE TABLE owner_t (id int PRIMARY KEY, code text UNIQUE)',
      'CREATE TABLE pet (id int PRIMARY KEY, owner_id int REFERENCES owner_t (id) ON DELETE CASCADE, alt_owner int REFERENCES owner_t (id) ON DELETE SET NULL ON UPDATE CASCADE, name text NOT NULL, CONSTRAINT pet_name_len CHECK (length(name) > 1))',
      "INSERT INTO owner_t VALUES (1, 'a'), (2, 'b')",
      "INSERT INTO pet VALUES (1, 1, 2, 'rex'), (2, 2, 1, 'tom'), (3, 1, NULL, 'kit')",
      "INSERT INTO pet VALUES (4, 3, NULL, 'bad')",
      "INSERT INTO pet VALUES (4, 1, NULL, 'x')",
      'INSERT INTO pet VALUES (4, 1, NULL, NULL)',
      "INSERT INTO pet VALUES (1, 1, NULL, 'dup')",
      "INSERT INTO owner_t VALUES (3, 'a')",
      'UPDATE owner_t SET id = 20 WHERE id = 2',
      'UPDATE owner_t SET id = 10 WHERE id = 1',
      'DELETE FROM owner_t WHERE id = 2',
      'SELECT id, owner_id, alt_owner, name FROM pet ORDER BY id',
      'CREATE TABLE strict_child (id int PRIMARY KEY, owner_id int REFERENCES owner_t ON DELETE RESTRICT)',
      'INSERT INTO strict_child VALUES (1, 1)',
      'DELETE FROM owner_t WHERE id = 1',
      'CREATE TABLE deferred_child (id int PRIMARY KEY, owner_id int REFERENCES owner_t DEFERRABLE INITIALLY DEFERRED)',
      'INSERT INTO deferred_child VALUES (1, 99)',
      'SET CONSTRAINTS ALL IMMEDIATE',
      'CREATE TABLE excl (a int, b int, UNIQUE (a, b), UNIQUE NULLS NOT DISTINCT (b))',
      'INSERT INTO excl VALUES (1, NULL), (1, NULL)',
      'INSERT INTO excl VALUES (2, NULL)',
      'ALTER TABLE pet ADD CONSTRAINT pet_id_positive CHECK (id > 1)',
      'ALTER TABLE pet ADD CONSTRAINT pet_id_positive CHECK (id > 0) NOT VALID',
      "SELECT conname, contype, pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid = 'pet'::regclass ORDER BY conname COLLATE \"C\"",
    ],
  },
  {
    name: 'sequences, serial and identity',
    statements: [
      'CREATE SEQUENCE seq_a START 10 INCREMENT 5',
      "SELECT nextval('seq_a'), nextval('seq_a'), currval('seq_a'), setval('seq_a', 100), nextval('seq_a'), setval('seq_a', 7, false), nextval('seq_a')",
      "SELECT currval('seq_missing')",
      'CREATE SEQUENCE seq_b MAXVALUE 2',
      "SELECT nextval('seq_b'), nextval('seq_b')",
      "SELECT nextval('seq_b')",
      'CREATE SEQUENCE seq_c',
      "SELECT currval('seq_c')",
      'CREATE TABLE ident (id int GENERATED ALWAYS AS IDENTITY, by_default bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 100), s smallserial, label text)',
      "INSERT INTO ident (label) VALUES ('a'), ('b') RETURNING id, by_default, s",
      "INSERT INTO ident (id, label) VALUES (50, 'forced')",
      "INSERT INTO ident (id, label) OVERRIDING SYSTEM VALUE VALUES (50, 'forced') RETURNING id",
      "INSERT INTO ident (by_default, label) VALUES (5, 'x') RETURNING by_default",
      "SELECT pg_get_serial_sequence('ident', 's'), pg_get_serial_sequence('ident', 'id')",
      'ALTER TABLE ident ALTER COLUMN id RESTART WITH 1000',
      "INSERT INTO ident (label) VALUES ('c') RETURNING id",
      'SELECT last_value, is_called FROM seq_a',
      "SELECT sequence_name, start_value FROM pg_sequences WHERE schemaname = 'sql_parity'",
      "SELECT sequencename, start_value, increment_by, max_value, last_value FROM pg_sequences WHERE schemaname = 'sql_parity' ORDER BY sequencename COLLATE \"C\"",
    ],
  },
  {
    name: 'DDL and views',
    statements: [
      'CREATE TABLE ddl_t (id int PRIMARY KEY, a text)',
      "INSERT INTO ddl_t VALUES (1, 'x'), (2, 'y')",
      "ALTER TABLE ddl_t ADD COLUMN b int NOT NULL DEFAULT 5, ADD COLUMN c text DEFAULT 'c'",
      'SELECT * FROM ddl_t ORDER BY id',
      'ALTER TABLE ddl_t ADD COLUMN d int NOT NULL',
      'ALTER TABLE ddl_t ALTER COLUMN b TYPE text USING b::text || \'!\'',
      'ALTER TABLE ddl_t ALTER COLUMN a TYPE int',
      'ALTER TABLE ddl_t ALTER COLUMN a SET NOT NULL, ALTER COLUMN c DROP DEFAULT',
      "INSERT INTO ddl_t (id, a, b) VALUES (3, 'z', 'q') RETURNING *",
      'ALTER TABLE ddl_t RENAME COLUMN a TO letter',
      'ALTER TABLE ddl_t RENAME TO ddl_renamed',
      'ALTER TABLE ddl_renamed DROP COLUMN c',
      'SELECT * FROM ddl_renamed ORDER BY id',
      'SELECT * FROM ddl_t',
      "SELECT column_name, data_type, is_nullable, column_default FROM information_schema.columns WHERE table_schema = 'sql_parity' AND table_name = 'ddl_renamed' ORDER BY ordinal_position",
      'CREATE VIEW v_ddl AS SELECT id, upper(letter) AS l FROM ddl_renamed WHERE id > 1',
      'SELECT * FROM v_ddl ORDER BY id',
      "INSERT INTO v_ddl (id) VALUES (9)",
      "SELECT pg_get_viewdef('v_ddl'::regclass, true)",
      'DROP TABLE ddl_renamed',
      'DROP TABLE ddl_renamed CASCADE',
      'SELECT * FROM v_ddl',
      'CREATE TABLE ddl_t2 (LIKE emp_missing)',
      'CREATE TABLE IF NOT EXISTS ddl_t2 (x int)',
      'CREATE TABLE IF NOT EXISTS ddl_t2 (x int)',
      'CREATE TABLE ddl_t2 (x int)',
      'CREATE INDEX ddl_idx ON ddl_t2 (x) WHERE x > 0',
      'CREATE UNIQUE INDEX ddl_uidx ON ddl_t2 (lower(x::text))',
      "SELECT indexname, indexdef FROM pg_indexes WHERE schemaname = 'sql_parity' ORDER BY indexname COLLATE \"C\"",
      'TRUNCATE ddl_t2',
      'CREATE MATERIALIZED VIEW mv AS SELECT 1 AS one',
      'REFRESH MATERIALIZED VIEW mv',
      'SELECT * FROM mv',
      "COMMENT ON TABLE ddl_t2 IS 'a comment'",
      "SELECT obj_description('ddl_t2'::regclass, 'pg_class')",
    ],
  },
  {
    // The statements linkgress's model-managed views (`model.view()`) run: create, stamp the
    // marker comment, read it back through pg_class, drop, re-create without a comment.
    name: 'model-managed view lifecycle: create, marker comment, drop, re-create',
    statements: [
      'CREATE TABLE parity_view_base (id int PRIMARY KEY, amount int NOT NULL)',
      'INSERT INTO parity_view_base VALUES (1, 1500)',
      'CREATE VIEW parity_view_v AS SELECT id, amount / 100 AS amount_eur FROM parity_view_base',
      "COMMENT ON VIEW parity_view_v IS 'linkgress:view:sha256:abc'",
      "SELECT c.relname, obj_description(c.oid, 'pg_class') AS marker FROM pg_class c WHERE c.relkind = 'v' AND c.relname = 'parity_view_v'",
      'SELECT id, amount_eur FROM parity_view_v',
      'DROP VIEW IF EXISTS parity_view_v',
      "SELECT count(*)::int AS n FROM pg_class WHERE relkind = 'v' AND relname = 'parity_view_v'",
      'CREATE VIEW parity_view_v AS SELECT id FROM parity_view_base',
      "SELECT obj_description(c.oid, 'pg_class') AS marker FROM pg_class c WHERE c.relkind = 'v' AND c.relname = 'parity_view_v'",
      'DROP VIEW parity_view_v',
      'DROP TABLE parity_view_base',
    ],
  },
  {
    name: 'PL/pgSQL functions',
    statements: [
      `CREATE FUNCTION fact(n int) RETURNS numeric LANGUAGE plpgsql IMMUTABLE AS $$
        DECLARE r numeric := 1;
        BEGIN
          IF n < 0 THEN RAISE EXCEPTION 'negative: %', n USING ERRCODE = '22023', HINT = 'pass n >= 0'; END IF;
          FOR i IN 2..n LOOP r := r * i; END LOOP;
          RETURN r;
        END $$`,
      'SELECT fact(0), fact(5), fact(25)',
      'SELECT fact(-1)',
      `CREATE FUNCTION safe_div(a int, b int) RETURNS text LANGUAGE plpgsql AS $$
        BEGIN
          RETURN (a / b)::text;
        EXCEPTION
          WHEN division_by_zero THEN RETURN 'div0: ' || SQLERRM || ' ' || SQLSTATE;
          WHEN OTHERS THEN RETURN 'other';
        END $$`,
      'SELECT safe_div(7, 2), safe_div(1, 0)',
      `CREATE FUNCTION evens(maxn int) RETURNS TABLE (n int, sq int) LANGUAGE plpgsql AS $$
        BEGIN
          FOR n IN SELECT g FROM generate_series(1, maxn) g WHERE g % 2 = 0 LOOP
            sq := n * n;
            RETURN NEXT;
          END LOOP;
          RETURN QUERY SELECT -1, -1;
        END $$`,
      'SELECT * FROM evens(6)',
      `CREATE FUNCTION loops() RETURNS text LANGUAGE plpgsql AS $$
        DECLARE s text := ''; i int := 0; arr int[] := ARRAY[3, 4]; x int; rec record;
        BEGIN
          WHILE i < 3 LOOP i := i + 1; CONTINUE WHEN i = 2; s := s || i; END LOOP;
          LOOP i := i + 1; EXIT WHEN i > 5; END LOOP;
          FOREACH x IN ARRAY arr LOOP s := s || ':' || x; END LOOP;
          FOR rec IN SELECT 'r' || g AS v FROM generate_series(1, 2) g LOOP s := s || rec.v; END LOOP;
          CASE i WHEN 6 THEN s := s || '#six'; ELSE s := s || '#?'; END CASE;
          RETURN s;
        END $$`,
      'SELECT loops()',
      `CREATE FUNCTION raiser(kind text) RETURNS void LANGUAGE plpgsql AS $$
        BEGIN
          IF kind = 'custom' THEN RAISE SQLSTATE 'P0099' USING MESSAGE = 'custom failure', DETAIL = 'some detail';
          ELSIF kind = 'unique' THEN RAISE unique_violation USING MESSAGE = 'fake unique';
          ELSE RAISE 'plain % and %', kind, 42;
          END IF;
        END $$`,
      "SELECT raiser('custom')",
      "SELECT raiser('unique')",
      "SELECT raiser('x')",
      `CREATE FUNCTION out_params(a int, OUT doubled int, OUT label text) LANGUAGE plpgsql AS $$ BEGIN doubled := a * 2; label := 'n' || a; END $$`,
      'SELECT out_params(4), (out_params(5)).label, * FROM out_params(6)',
      `CREATE FUNCTION sql_fn(x int, y int DEFAULT 10) RETURNS int LANGUAGE sql AS $$ SELECT x + y $$`,
      'SELECT sql_fn(1), sql_fn(1, 2), sql_fn(y => 3, x => 1)',
      'SELECT sql_fn()',
      'SELECT sql_fn(1, 2, 3)',
      `CREATE FUNCTION dyn(tbl text) RETURNS bigint LANGUAGE plpgsql AS $$ DECLARE c bigint; BEGIN EXECUTE format('SELECT count(*) FROM %I', tbl) INTO c; RETURN c; END $$`,
      "SELECT dyn('pg_am') > 0",
      "SELECT dyn('no_such_table')",
      `DO $$ DECLARE v int; BEGIN SELECT 1 INTO STRICT v FROM generate_series(1, 2); END $$`,
      `DO $$ BEGIN PERFORM 1 / 0; END $$`,
      `CREATE FUNCTION broken() RETURNS int LANGUAGE plpgsql AS $$ BEGIN RETURN undefined_var; END $$`,
      'SELECT broken()',
      // a data-modifying statement's RETURNING ... INTO is a plpgsql target list, INSERT INTO / MERGE INTO are not
      'CREATE TABLE ri (id serial PRIMARY KEY, n int)',
      `DO $$ DECLARE v int; BEGIN INSERT INTO ri (n) VALUES (1) RETURNING id INTO v; INSERT INTO ri (n) VALUES (v * 100); END $$`,
      `DO $$ DECLARE a int; b int; BEGIN UPDATE ri SET n = n + 1 WHERE id = 1 RETURNING id, n INTO a, b; INSERT INTO ri (n) VALUES (a * 1000 + b); END $$`,
      `DO $$ DECLARE v int; BEGIN DELETE FROM ri WHERE n = 100 RETURNING n INTO v; INSERT INTO ri (n) VALUES (COALESCE(v, -1)); END $$`,
      `DO $$ DECLARE v int; BEGIN INSERT INTO ri (n) VALUES (7) RETURNING id INTO STRICT v; END $$`,
      `DO $$ DECLARE v int; BEGIN UPDATE ri SET n = 0 WHERE id = 9999 RETURNING id INTO STRICT v; END $$`,
      `DO $$ DECLARE v int; BEGIN UPDATE ri SET n = n WHERE id IS NOT NULL RETURNING id INTO STRICT v; END $$`,
      `DO $$ DECLARE v int := 5; BEGIN UPDATE ri SET n = 0 WHERE id = 9999 RETURNING id INTO v; IF v IS NOT NULL THEN RAISE 'expected NULL'; END IF; END $$`,
      `DO $$ DECLARE v int; BEGIN WITH c AS (SELECT 21 AS x) INSERT INTO ri (n) SELECT x FROM c RETURNING id INTO v; INSERT INTO ri (n) VALUES (v); END $$`,
      `DO $$ DECLARE v int; BEGIN MERGE INTO ri USING (SELECT 1 AS k) s ON ri.id = 1 WHEN MATCHED THEN UPDATE SET n = n RETURNING ri.id INTO v; INSERT INTO ri (n) VALUES (v); END $$`,
      `CREATE FUNCTION ins_ret(p int) RETURNS int LANGUAGE plpgsql AS $$ DECLARE v int; BEGIN INSERT INTO ri (n) VALUES (p) RETURNING id INTO v; RETURN v; END $$`,
      'SELECT ins_ret(42) > 0',
      'SELECT id, n FROM ri ORDER BY id',
      // ("INTO specified more than once" is covered in in-memory-database.test.ts: it is a plpgsql PARSE
      //  error, and the engine reports no position for those — a gap of its own, not of the INTO clause)
      `DO $$ BEGIN INSERT INTO ri (n) VALUES (3) RETURNING id; END $$`,
      `DO $$ BEGIN SELECT 1; END $$`,
      `DO $$ BEGIN INSERT INTO no_such_table (n) VALUES (1); END $$`,
      `DO $$ DECLARE v int; BEGIN INSERT INTO no_such_table (n) VALUES (1) RETURNING id INTO v; END $$`,
    ],
  },
  {
    name: 'triggers',
    statements: [
      'CREATE TABLE acct (id int PRIMARY KEY, balance int NOT NULL, updated_count int DEFAULT 0, tag text)',
      'CREATE TABLE acct_log (seq serial, op text, acct_id int, old_balance int, new_balance int)',
      `CREATE FUNCTION acct_before() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF NEW.balance < 0 THEN RAISE EXCEPTION 'balance cannot be negative (%)', NEW.balance; END IF;
          IF TG_OP = 'UPDATE' THEN NEW.updated_count := OLD.updated_count + 1; END IF;
          NEW.tag := lower(TG_OP) || ':' || TG_WHEN || ':' || TG_TABLE_NAME;
          RETURN NEW;
        END $$`,
      `CREATE FUNCTION acct_after() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          INSERT INTO acct_log (op, acct_id, old_balance, new_balance)
          VALUES (TG_OP, coalesce(NEW.id, OLD.id), CASE WHEN TG_OP <> 'INSERT' THEN OLD.balance END, CASE WHEN TG_OP <> 'DELETE' THEN NEW.balance END);
          RETURN NULL;
        END $$`,
      'CREATE TRIGGER t_before BEFORE INSERT OR UPDATE ON acct FOR EACH ROW EXECUTE FUNCTION acct_before()',
      'CREATE TRIGGER t_after AFTER INSERT OR UPDATE OR DELETE ON acct FOR EACH ROW EXECUTE FUNCTION acct_after()',
      'INSERT INTO acct (id, balance) VALUES (1, 100), (2, 50) RETURNING *',
      'UPDATE acct SET balance = balance - 30 RETURNING id, balance, updated_count, tag',
      'UPDATE acct SET balance = -1 WHERE id = 2',
      'DELETE FROM acct WHERE id = 1',
      'SELECT op, acct_id, old_balance, new_balance FROM acct_log ORDER BY seq',
      `CREATE FUNCTION skip_odd() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.id % 2 = 1 THEN RETURN NULL; END IF; RETURN NEW; END $$`,
      'CREATE TRIGGER t_skip BEFORE INSERT ON acct FOR EACH ROW WHEN (NEW.balance > 1000) EXECUTE FUNCTION skip_odd()',
      'INSERT INTO acct (id, balance) VALUES (3, 5000), (4, 5000), (5, 10)',
      'SELECT id, balance FROM acct ORDER BY id',
      `CREATE FUNCTION stmt_trig() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE NOTICE 'statement %', TG_OP; INSERT INTO acct_log (op) VALUES ('STMT ' || TG_OP); RETURN NULL; END $$`,
      'CREATE TRIGGER t_stmt AFTER UPDATE ON acct FOR EACH STATEMENT EXECUTE FUNCTION stmt_trig()',
      'UPDATE acct SET balance = balance WHERE false',
      "SELECT op FROM acct_log WHERE op LIKE 'STMT%'",
    ],
  },
  {
    name: 'enum, domain and composite types',
    statements: [
      "CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy')",
      'CREATE TABLE person_mood (name text, m mood)',
      "INSERT INTO person_mood VALUES ('a', 'happy'), ('b', 'sad'), ('c', 'ok'), ('d', NULL)",
      "SELECT name, m FROM person_mood ORDER BY m NULLS FIRST",
      "SELECT m > 'sad', m::text, enum_range(NULL::mood), enum_first(NULL::mood) FROM person_mood WHERE name = 'c'",
      "INSERT INTO person_mood VALUES ('e', 'angry')",
      "SELECT 'happy'::mood < 'ok'::mood, array_agg(m ORDER BY m) FROM person_mood",
      "CREATE DOMAIN pos_int AS int CHECK (VALUE > 0) NOT NULL",
      'CREATE TABLE dom_t (v pos_int)',
      'INSERT INTO dom_t VALUES (5)',
      'INSERT INTO dom_t VALUES (0)',
      'INSERT INTO dom_t VALUES (NULL)',
      "SELECT 3::pos_int + 1, pg_typeof(3::pos_int), (-1)::pos_int",
      'CREATE TYPE point3 AS (x int, y int, z int)',
      'CREATE TABLE shapes (id int, p point3, pts point3[])',
      "INSERT INTO shapes VALUES (1, ROW(1, 2, 3), ARRAY[ROW(1,1,1)::point3, ROW(2,2,2)::point3]), (2, '(4,5,)', '{}')",
      'SELECT id, p, (p).x, (p).z IS NULL, pts[2], (pts[1]).y FROM shapes ORDER BY id',
      'UPDATE shapes SET p.y = 20 WHERE id = 1 RETURNING p',
      'SELECT ROW(1, \'a\') = ROW(1, \'a\'), ROW(1, NULL) IS NULL, ROW(NULL, NULL) IS NULL, (ROW(1, 2)).f1',
      "SELECT '(1,2)'::point3",
      "SELECT s FROM shapes s ORDER BY id",
    ],
  },
  {
    name: 'generated columns and partitioning',
    statements: [
      'CREATE TABLE gen_bad (qty int, label text GENERATED ALWAYS AS (upper(\'x\') || qty) STORED)',
      'CREATE TABLE gen_bad2 (qty int, label text GENERATED ALWAYS AS (\'x\' || qty) STORED)',
      'CREATE TABLE gen (price numeric(10,2), qty int, code text, total numeric GENERATED ALWAYS AS (price * qty) STORED, label text GENERATED ALWAYS AS (upper(code) || \':\' || qty::text) STORED)',
      "INSERT INTO gen (price, qty, code) VALUES (1.50, 3, 'ab'), (2, NULL, 'c') RETURNING *",
      'INSERT INTO gen (price, qty, total) VALUES (1, 1, 99)',
      'UPDATE gen SET qty = 10 WHERE qty = 3 RETURNING total, label',
      'CREATE TABLE measurement (id int, logdate date, value int) PARTITION BY RANGE (logdate)',
      "CREATE TABLE measurement_2024_01 PARTITION OF measurement FOR VALUES FROM ('2024-01-01') TO ('2024-02-01')",
      "CREATE TABLE measurement_2024_02 PARTITION OF measurement FOR VALUES FROM ('2024-02-01') TO ('2024-03-01')",
      'CREATE TABLE measurement_other PARTITION OF measurement DEFAULT',
      "INSERT INTO measurement VALUES (1, '2024-01-15', 10), (2, '2024-02-20', 20), (3, '2025-01-01', 30)",
      'SELECT tableoid::regclass, * FROM measurement ORDER BY id',
      "UPDATE measurement SET logdate = '2024-01-02' WHERE id = 2",
      'SELECT tableoid::regclass, id FROM measurement ORDER BY id',
      'SELECT count(*) FROM measurement_2024_01',
      'CREATE TABLE lp (k text, v int) PARTITION BY LIST (k)',
      "CREATE TABLE lp_a PARTITION OF lp FOR VALUES IN ('a', 'b')",
      "INSERT INTO lp VALUES ('c', 1)",
      'CREATE TABLE hp (id int) PARTITION BY HASH (id)',
      'CREATE TABLE hp0 PARTITION OF hp FOR VALUES WITH (MODULUS 2, REMAINDER 0)',
      'CREATE TABLE hp1 PARTITION OF hp FOR VALUES WITH (MODULUS 2, REMAINDER 1)',
      'INSERT INTO hp SELECT generate_series(1, 10)',
      'SELECT tableoid::regclass, count(*) FROM hp GROUP BY 1 ORDER BY 1',
    ],
  },
  {
    name: 'ranges',
    statements: [
      "SELECT int4range(1, 5), int4range(1, 5, '[]'), '[1,5)'::int4range @> 3, int4range(1, 5) && int4range(5, 7), numrange(1.5, 2.5) * numrange(2, 3)",
      "SELECT lower(daterange('2024-01-01', '2024-02-01')), upper_inc('[1,2]'::int4range), isempty('empty'::int4range), int8range(1, 10) - int8range(5, 20), int4range(1, 3) + int4range(3, 5)",
      "SELECT tstzrange('2024-01-01 00:00+00', '2024-01-02 00:00+00') @> timestamptz '2024-01-01 12:00+00', '[2024-01-01,2024-01-10)'::daterange -|- '[2024-01-10,2024-01-20)'::daterange",
      "SELECT int4range(5, 1)",
      "SELECT int4range(1, 3) + int4range(5, 7)",
      "SELECT '{[1,3), [5,7)}'::int4multirange, range_merge(int4range(1, 2), int4range(5, 6)), int4range(NULL, 5), '(,)'::int4range",
      'SELECT r FROM (VALUES (int4range(3, 5)), (int4range(1, 9)), (int4range(1, 2)), (\'empty\'::int4range)) v(r) ORDER BY r',
    ],
  },
  {
    name: 'uuid, bytea and boolean output',
    statements: [
      "SELECT 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'::uuid = 'A0EEBC99-9C0B-4EF8-BB6D-6BB9BD380A11', '{a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11}'::uuid, 'a0eebc999c0b4ef8bb6d6bb9bd380a11'::uuid",
      "SELECT length(gen_random_uuid()::text), uuid_extract_version('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11')",
      "SELECT md5('x')::uuid, 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'::uuid < 'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'::uuid",
      "SELECT '\\xDEADBEEF'::bytea, length('\\xDEADBEEF'::bytea), get_byte('\\x0102'::bytea, 1), set_byte('\\x0102'::bytea, 0, 255), substring('\\x01020304'::bytea from 2 for 2), '\\x01'::bytea || '\\x02'::bytea",
      "SELECT encode('\\x00ff'::bytea, 'escape'), encode('ab'::bytea, 'hex'), decode('YWJj', 'base64'), sha256('abc'::bytea), md5('abc'::bytea)",
      "SELECT convert_from('\\x68c3a9'::bytea, 'UTF8'), 'abc'::bytea = 'abc'::bytea, position('\\x02'::bytea in '\\x010203'::bytea)",
      "SELECT true::text, false::varchar, 't'::bool AND 'f'::bool, 1::boolean, 0::boolean, 'TRUE'::boolean, bool_or(x) FROM (VALUES (true), (NULL)) v(x)",
      "SELECT '\\xZZ'::bytea",
      'SELECT 2::boolean',
      // a boolean COLUMN goes over the wire as its output function writes it, t / f ...
      'SELECT true AS a, false AS b, NULL::boolean AS c, ARRAY[true, false] AS d, ROW(true, false) AS e',
      "SELECT b, b IS TRUE FROM (VALUES (true), (false), (NULL::boolean)) v(b) ORDER BY b NULLS LAST",
      // ... but a boolean CONVERTED to text inside SQL is the pg_cast function, true / false
      "SELECT 'x' || true, true || 'x', 'x' || (1 IS NULL), 'p:' || (1 = 1), true::text || false::text",
      "SELECT string_agg(i || ':' || b, ',' ORDER BY i) FROM (VALUES (1, true), (2, false)) v(i, b)",
      "SELECT length('x' || true), ('x' || true) = 'xtrue', (true::text)::boolean",
      // the two paths disagree on purpose: quote_literal casts, format() and concat() call the output function
      "SELECT quote_literal(true), quote_nullable(false), quote_nullable(NULL::boolean), format('%L', true), format('%s', true), concat('x', true)",
      "SELECT quote_literal('a  '::char(4)), format('%L', 'a  '::char(4)), 'a'::char(4) || 'x', quote_literal(1), quote_literal(DATE '2024-01-02')",
      "SELECT to_json(true), to_jsonb(false), jsonb_build_object('k', true), to_jsonb(r) FROM (SELECT true AS a, false AS b) r",
    ],
  },
  {
    name: 'bind parameters',
    statements: [
      'CREATE TABLE prm (id int PRIMARY KEY, name text, price numeric(8,2), tags text[], data jsonb, at timestamptz)',
      p('INSERT INTO prm VALUES ($1, $2, $3, $4, $5, $6) RETURNING *', 1, 'first', '9.95', '{a,b}', '{"k": [1, 2]}', '2024-05-01T10:00:00Z'),
      p('INSERT INTO prm (id, name) VALUES ($1, $2), ($3, $4)', 2, 'second', 3, null),
      p('SELECT id, name FROM prm WHERE id = ANY ($1) ORDER BY id', '{1,3}'),
      p('SELECT $1::int + $2::int, $1 || $3', '4', '5', 'x'),
      p('SELECT name FROM prm WHERE name = $1 OR ($1 IS NULL AND name IS NULL)', null),
      p('SELECT data -> $1 ->> $2 FROM prm WHERE id = $3', 'k', '1', 1),
      p('SELECT $1::date + $2::int', '2024-02-28', 2),
      p('SELECT $1 + 1', 'abc'),
      p('SELECT $1::int', '1.5'),
      p('SELECT count(*) FROM prm WHERE price > $1', '5'),
      p('UPDATE prm SET tags = array_append(tags, $1) WHERE id = $2 RETURNING tags', 'c', 1),
      p('SELECT $1', 'untyped'),
      p('SELECT id FROM prm WHERE at < $1 ORDER BY id', '2025-01-01 00:00:00+00'),
      p('SELECT $2', 'only one'),
    ],
  },
  {
    name: 'trigger transition tables',
    statements: [
      'CREATE TABLE tt (id int PRIMARY KEY, v text, modified_by int)',
      'CREATE TABLE tt_log (op text, item int, diff jsonb)',
      `CREATE FUNCTION tt_log_fn() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO tt_log SELECT TG_OP, (to_jsonb(nr)->>'id')::int, to_jsonb(nr) FROM new_rows nr;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO tt_log
    SELECT TG_OP, (to_jsonb(nr)->>'id')::int, diff.value_diff
    FROM new_rows nr JOIN old_rows orw ON (to_jsonb(orw)->>'id')::int = (to_jsonb(nr)->>'id')::int
    CROSS JOIN LATERAL (
      SELECT array_to_json(array_agg(row_to_json(x)))::jsonb AS value_diff
      FROM (SELECT pre.key AS c, pre.value AS o, post.value AS n
            FROM jsonb_each(to_jsonb(orw)) pre JOIN jsonb_each(to_jsonb(nr)) post ON pre.key = post.key
            WHERE pre.value IS DISTINCT FROM post.value) x
    ) diff
    WHERE diff.value_diff IS NOT NULL;
  ELSE
    INSERT INTO tt_log SELECT TG_OP, (to_jsonb(orw)->>'id')::int, to_jsonb(orw) FROM old_rows orw;
  END IF;
  RETURN NULL;
END $$`,
      'CREATE TRIGGER tt_ins AFTER INSERT ON tt REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE PROCEDURE tt_log_fn()',
      'CREATE TRIGGER tt_upd AFTER UPDATE ON tt REFERENCING NEW TABLE AS new_rows OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE PROCEDURE tt_log_fn()',
      'CREATE TRIGGER tt_del AFTER DELETE ON tt REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE PROCEDURE tt_log_fn()',
      "INSERT INTO tt VALUES (1, 'a', 7), (2, 'b', NULL)",
      "UPDATE tt SET v = v || '!' WHERE id = 1",
      'UPDATE tt SET v = v WHERE id = 2',
      "INSERT INTO tt VALUES (2, 'c', 1) ON CONFLICT (id) DO UPDATE SET v = excluded.v",
      'DELETE FROM tt WHERE id = 2',
      'SELECT op, item, diff FROM tt_log ORDER BY op COLLATE "C", item, diff::text COLLATE "C"',
      "SELECT tgname, tgoldtable, tgnewtable FROM pg_trigger WHERE tgrelid = 'tt'::regclass ORDER BY tgname",
      'CREATE TABLE tp (id int, v int) PARTITION BY RANGE (id)',
      'CREATE TABLE tp1 PARTITION OF tp FOR VALUES FROM (0) TO (10)',
      'CREATE TABLE tp2 PARTITION OF tp FOR VALUES FROM (10) TO (20)',
      `CREATE FUNCTION tp_fn() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO tt_log SELECT 'tp', count(*), jsonb_agg(to_jsonb(p) ORDER BY p.id) FROM np p;
  RETURN NULL;
END $$`,
      'CREATE TRIGGER tp_ins AFTER INSERT ON tp REFERENCING NEW TABLE AS np FOR EACH STATEMENT EXECUTE FUNCTION tp_fn()',
      'INSERT INTO tp VALUES (1, 1), (15, 2)',
      "SELECT item, diff FROM tt_log WHERE op = 'tp'",
      'CREATE TRIGGER bad_before BEFORE INSERT ON tp REFERENCING NEW TABLE AS nt FOR EACH STATEMENT EXECUTE FUNCTION tp_fn()',
      'CREATE TRIGGER bad_events AFTER INSERT OR UPDATE ON tt REFERENCING NEW TABLE AS nt FOR EACH STATEMENT EXECUTE FUNCTION tp_fn()',
      'CREATE TRIGGER bad_old AFTER INSERT ON tt REFERENCING OLD TABLE AS ot FOR EACH STATEMENT EXECUTE FUNCTION tp_fn()',
      'CREATE TRIGGER bad_same AFTER UPDATE ON tt REFERENCING NEW TABLE AS x OLD TABLE AS x FOR EACH STATEMENT EXECUTE FUNCTION tp_fn()',
      'CREATE TRIGGER bad_part AFTER INSERT ON tp1 REFERENCING NEW TABLE AS x FOR EACH ROW EXECUTE FUNCTION tp_fn()',
      'SELECT * FROM new_rows',
    ],
  },
  {
    // the in-memory engine reuses a statement's analysis (prepared statements, function bodies, repeated
    // texts): each change it depends on must show in the next run
    name: 'reused statement analysis sees what changed',
    statements: [
      'CREATE SCHEMA ra2',
      'CREATE TABLE ra (id int, v text)',
      'CREATE TABLE ra2.ra (id int, v text, extra int)',
      "INSERT INTO ra VALUES (1, 'public')",
      "INSERT INTO ra2.ra VALUES (2, 'ra2', 22)",
      'PREPARE ra_q AS SELECT * FROM ra ORDER BY id',
      'EXECUTE ra_q',
      'SELECT * FROM ra ORDER BY id',
      'SET search_path = ra2, public',
      'EXECUTE ra_q',
      'SELECT * FROM ra ORDER BY id',
      'DEALLOCATE ra_q',
      'SET search_path = sql_parity, public',
      'SELECT * FROM ra ORDER BY id',
      'ALTER TABLE ra ADD COLUMN added int DEFAULT 5',
      'SELECT * FROM ra ORDER BY id',
      "INSERT INTO ra VALUES (3, 'after alter')",
      'SELECT * FROM ra ORDER BY id',
      'ALTER TABLE ra DROP COLUMN v',
      "INSERT INTO ra VALUES (4, 'dropped')",
      'INSERT INTO ra VALUES (4, 40)',
      'SELECT * FROM ra ORDER BY id',
      p('SELECT $1::int + 1', 1),
      p('SELECT $1::int + 1', '2'),
      "SET TIME ZONE 'UTC'",
      "SELECT '2024-06-01 12:00'::timestamptz::text, '2024-06-01 12:00'::timestamptz",
      "SET TIME ZONE 'Asia/Tokyo'",
      "SELECT '2024-06-01 12:00'::timestamptz::text, '2024-06-01 12:00'::timestamptz",
      // one trigger function over tables of different shapes, and after its table changed
      'CREATE TABLE ra_log (tbl text, row_json jsonb)',
      `CREATE FUNCTION ra_log_fn() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO ra_log SELECT TG_TABLE_NAME, to_jsonb(n) FROM new_rows n;
  RETURN NULL;
END $$`,
      'CREATE TABLE ra_a (id int, a text)',
      'CREATE TABLE ra_b (id int, b numeric, c bool)',
      'CREATE TRIGGER ra_a_ins AFTER INSERT ON ra_a REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION ra_log_fn()',
      'CREATE TRIGGER ra_b_ins AFTER INSERT ON ra_b REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION ra_log_fn()',
      "INSERT INTO ra_a VALUES (1, 'x')",
      'INSERT INTO ra_b VALUES (1, 1.50, true), (2, NULL, false)',
      "INSERT INTO ra_a VALUES (2, 'y'), (3, NULL)",
      'ALTER TABLE ra_a ADD COLUMN z int',
      "INSERT INTO ra_a VALUES (4, 'w', 44)",
      'INSERT INTO ra_b VALUES (3, 3, NULL)',
      'SELECT tbl, row_json FROM ra_log ORDER BY tbl COLLATE "C", row_json::text COLLATE "C"',
      'DROP TRIGGER ra_b_ins ON ra_b',
      'INSERT INTO ra_b VALUES (9, 9, true)',
      'SELECT count(*) FROM ra_log',
    ],
  },
  {
    name: 'PREPARE / EXECUTE, INSERT targets and expression contexts',
    statements: [
      'CREATE DOMAIN pos_int AS int CHECK (VALUE > 0)',
      'CREATE TABLE pe (a pos_int, b text)',
      'PREPARE pe_ins(pos_int, text) AS INSERT INTO pe VALUES ($1, $2) RETURNING *',
      "EXECUTE pe_ins(1, 'x')",
      "EXECUTE pe_ins('3', 4)",
      "EXECUTE pe_ins(0, 'y')",
      'PREPARE pe_sel AS SELECT * FROM pe WHERE a > $1 ORDER BY a',
      'EXECUTE pe_sel(0)',
      'EXECUTE pe_sel',
      "EXECUTE pe_sel('x')",
      'EXECUTE pe_sel((SELECT 1))',
      'EXECUTE pe_sel(count(*))',
      p('EXECUTE pe_sel($1)', 1),
      'SELECT name, statement, parameter_types, result_types, from_sql FROM pg_prepared_statements ORDER BY name COLLATE "C"',
      'EXPLAIN (COSTS OFF) EXECUTE pe_ins(6, \'z\')',
      'CREATE TABLE pe_copy AS EXECUTE pe_sel(1)',
      'CREATE TABLE pe_bad AS EXECUTE pe_ins(7, \'q\')',
      'ALTER TABLE pe ADD COLUMN c int',
      'EXECUTE pe_sel(0)',
      'DEALLOCATE pe_sel',
      'EXECUTE pe_sel(1)',
      'PREPARE pe_bad2(int) AS SELECT $2',
      'DEALLOCATE ALL',
      'CREATE TYPE pe_pair AS (x int, y text)',
      "CREATE TABLE pt (id int, arr int[], c pe_pair, ta text[] DEFAULT '{d}')",
      'INSERT INTO pt (id, arr[2], c.x) VALUES (1, 5, 7) RETURNING *',
      "INSERT INTO pt (id, arr[1], arr[3], c.x, c.y) VALUES (2, 1, 3, 1, 'a') RETURNING *",
      "INSERT INTO pt (id, arr[1:2], ta[2]) VALUES (3, '{8,9}', 'z') RETURNING *",
      'INSERT INTO pt (id, arr[1], arr[2]) SELECT g, g * 2, g * 3 FROM generate_series(4, 5) g RETURNING *',
      'INSERT INTO pt (id, arr[1]) VALUES (6, DEFAULT)',
      "INSERT INTO pt (id, arr, arr[1]) VALUES (7, '{1}', 2)",
      'INSERT INTO pt (id, c.z) VALUES (8, 1)',
      "INSERT INTO pt (id, arr[1]) SELECT 9, 'x'",
      'CREATE TABLE gen_fold (q int, a text GENERATED ALWAYS AS (upper(\'x\' COLLATE "C") || q) STORED)',
      "CREATE TABLE gen_fold2 (q int, a boolean GENERATED ALWAYS AS ('abc' LIKE 'a%') STORED)",
      'CREATE TABLE gen_fold3 (q text, a text GENERATED ALWAYS AS (upper(q)) STORED)',
      "ALTER TABLE gen_fold3 ADD COLUMN b text GENERATED ALWAYS AS (replace('abc', 'b', 'x') || q) STORED",
      'CREATE TABLE gen_sub (a int, b int GENERATED ALWAYS AS (a + (SELECT 1)) STORED)',
      'CREATE INDEX ON pt (id) WHERE id > (SELECT 1)',
      'CREATE DOMAIN dom_sub AS int CHECK (VALUE > (SELECT 1))',
      'CREATE TABLE part_sub (a int) PARTITION BY RANGE ((a + (SELECT 1)))',
      'ALTER TABLE pt ALTER COLUMN id TYPE bigint USING (SELECT 1)',
    ],
  },
  {
    name: 'ORDER BY, LIMIT, DISTINCT',
    statements: [
      'CREATE TABLE ord (id int, grp int, val numeric, s text)',
      "INSERT INTO ord VALUES (1, 1, 3.5, 'b'), (2, 1, NULL, 'a'), (3, 2, 1.25, 'c'), (4, 2, 3.5, NULL), (5, NULL, 0, 'a')",
      'SELECT id FROM ord ORDER BY val DESC, id',
      'SELECT id FROM ord ORDER BY val ASC NULLS FIRST, id DESC',
      'SELECT id FROM ord ORDER BY grp NULLS FIRST, val DESC NULLS LAST, id LIMIT 3 OFFSET 1',
      'SELECT DISTINCT grp FROM ord ORDER BY grp',
      'SELECT DISTINCT ON (grp) grp, id, val FROM ord ORDER BY grp, val DESC NULLS LAST, id',
      'SELECT id FROM ord ORDER BY id FETCH FIRST 2 ROWS ONLY',
      'SELECT val FROM ord ORDER BY val FETCH FIRST 1 ROW WITH TIES',
      'SELECT id, s FROM ord ORDER BY s COLLATE "C" NULLS FIRST, id',
      'SELECT id FROM ord ORDER BY 5',
      'SELECT DISTINCT grp FROM ord ORDER BY id',
      'SELECT id FROM ord LIMIT -1',
      'SELECT id FROM ord ORDER BY id LIMIT ALL OFFSET 3',
      'SELECT count(DISTINCT (grp, val)) FROM ord',
      'SELECT id AS x FROM ord ORDER BY x + 0 DESC LIMIT 2',
      'SELECT grp, count(*) FROM ord GROUP BY grp ORDER BY count(*) DESC, grp NULLS FIRST',
      'SELECT id FROM ord ORDER BY (SELECT 1)',
    ],
  },
  {
    name: 'executor fast paths: hashed IN, streaming GROUP BY, plain DISTINCT, date_trunc, JSON builders',
    statements: [
      'CREATE TABLE fp (id int, grp int, sub int8, day timestamp, at timestamptz, flag bool, label text)',
      "INSERT INTO fp SELECT g, g % 3, (g % 4)::int8, '1999-12-30 22:15:30.25'::timestamp + g * interval '7 hours 13 minutes', '1969-07-20 20:17:40+00'::timestamptz + g * interval '11 hours', g % 2 = 0, CASE WHEN g % 5 = 0 THEN NULL ELSE 'l' || (g % 3) END FROM generate_series(1, 40) g",
      'CREATE TABLE fp_in (v int8, t text)',
      "INSERT INTO fp_in VALUES (1, 'l1'), (2, NULL), (NULL, 'l0')",
      // x IN (uncorrelated sub-select): matches, no match with a NULL in the set, NULL on the left, empty set
      'SELECT id, grp IN (SELECT v FROM fp_in), sub IN (SELECT v FROM fp_in WHERE v IS NOT NULL), label IN (SELECT t FROM fp_in), grp IN (SELECT v FROM fp_in WHERE false) FROM fp ORDER BY id',
      'SELECT count(*) FROM fp WHERE sub IN (SELECT v FROM fp_in) AND flag IN (SELECT true)',
      "SELECT id FROM fp WHERE day IN (SELECT day FROM fp WHERE id % 7 = 0) AND label NOT IN (SELECT 'l2') ORDER BY id",
      // GROUP BY several keys whose leading keys repeat across neighbouring rows, FILTER, NULL arguments, HAVING
      // (input order of json_agg / array_agg without ORDER BY is unspecified: PostgreSQL may sort to group)
      'SELECT grp, sub, flag, count(*), count(label), sum(id) FILTER (WHERE flag), min(label COLLATE "C"), max(id), bool_or(label IS NULL), avg(id) FROM fp GROUP BY grp, sub, flag ORDER BY grp, sub, flag',
      "SELECT sub, json_agg(id ORDER BY id), string_agg(label, ',' ORDER BY id) FROM fp GROUP BY sub ORDER BY sub",
      'SELECT grp, date_trunc(\'day\', day) AS d, count(*) FROM fp GROUP BY 1, 2 HAVING count(*) > 1 ORDER BY 1, 2',
      'SELECT count(*), sum(id), max(label) FROM fp WHERE false',
      'SELECT grp FROM fp GROUP BY grp ORDER BY grp',
      // plain DISTINCT / DISTINCT ON without ORDER BY, LIMIT with ties
      'SELECT count(*) FROM (SELECT DISTINCT grp, flag FROM fp) q',
      'SELECT array_agg(g ORDER BY g) FROM (SELECT DISTINCT label AS g FROM fp) q',
      'SELECT grp, id FROM (SELECT DISTINCT ON (grp) grp, id FROM fp ORDER BY grp, id DESC) q ORDER BY grp',
      'SELECT count(*), min(grp), max(grp) FROM (SELECT id, grp FROM fp ORDER BY grp FETCH FIRST 2 ROWS WITH TIES) q',
      // date_trunc by fixed units, before and after the 2000-01-01 epoch, both timestamp types
      "SELECT id, date_trunc('day', day), date_trunc('hour', day), date_trunc('minute', day), date_trunc('second', day), date_trunc('milliseconds', day), date_trunc('week', day) FROM fp WHERE id <= 12 ORDER BY id",
      "SET TIME ZONE 'Europe/Bratislava'",
      "SELECT id, date_trunc('day', at), date_trunc('hour', at), date_trunc('Minutes', at), date_trunc('sec', at), date_trunc('day', at AT TIME ZONE 'UTC') FROM fp WHERE id <= 12 ORDER BY id",
      "SELECT date_trunc('day', '2024-03-31 01:30:00+00'::timestamptz), date_trunc('hour', '2024-10-27 00:30:00+00'::timestamptz), date_trunc('day', '1900-01-01 12:34:56.789'::timestamp)",
      "SELECT date_trunc('fortnight', now())",
      // JSON builders
      "SELECT json_build_array(id, day, at, flag, label, NULL, 1.50), json_build_object('id', id, 'day', day, 'l', label) FROM fp WHERE id <= 3 ORDER BY id",
      'SELECT json_build_array(), json_build_object(), json_build_array(VARIADIC ARRAY[1, 2])',
      "SELECT json_agg(json_build_array(grp, day) ORDER BY id) FROM fp WHERE id <= 4",
    ],
  },
  {
    name: 'locking and transactions',
    statements: [
      'CREATE TABLE lk (id int PRIMARY KEY, v int)',
      'INSERT INTO lk VALUES (1, 1), (2, 2)',
      'SELECT id FROM lk ORDER BY id FOR UPDATE',
      'SELECT id FROM lk WHERE id = 1 FOR NO KEY UPDATE SKIP LOCKED',
      'SELECT id FROM lk FOR SHARE NOWAIT',
      'SELECT count(*) FROM lk FOR UPDATE',
      'SELECT DISTINCT v FROM lk FOR UPDATE',
      'SAVEPOINT inner_sp',
      'UPDATE lk SET v = 10',
      'ROLLBACK TO SAVEPOINT inner_sp',
      'SELECT v FROM lk ORDER BY id',
      'ROLLBACK TO SAVEPOINT nope',
      "SELECT current_setting('transaction_isolation'), current_setting('search_path')",
      'SET LOCAL statement_timeout = 0',
      "SELECT set_config('application_name', 'parity', true), current_setting('application_name')",
      "SELECT current_setting('no.such_setting')",
      "SELECT current_setting('no.such_setting', true) IS NULL",
      'SHOW TimeZone',
      'SHOW DateStyle',
      'SET TRANSACTION ISOLATION LEVEL SERIALIZABLE',
    ],
  },
  {
    name: 'catalog functions and type names',
    statements: [
      'CREATE TABLE cat_t (id bigserial PRIMARY KEY, n numeric(12,4), v varchar(30), ts timestamptz(3), arr int[], j jsonb NOT NULL DEFAULT \'{}\')',
      "SELECT 'cat_t'::regclass::text, to_regclass('cat_t')::text, to_regclass('missing_t') IS NULL",
      "SELECT attname, format_type(atttypid, atttypmod), attnotnull, pg_get_expr(adbin, adrelid) FROM pg_attribute LEFT JOIN pg_attrdef ON adrelid = attrelid AND adnum = attnum WHERE attrelid = 'cat_t'::regclass AND attnum > 0 ORDER BY attnum",
      "SELECT format_type('int4'::regtype, NULL), 'varchar'::regtype, 'double precision'::regtype, 'timestamptz'::regtype::oid, 'int[]'::regtype",
      "SELECT 'no_such_type'::regtype",
      "SELECT pg_get_indexdef(indexrelid) FROM pg_index WHERE indrelid = 'cat_t'::regclass",
      "SELECT has_table_privilege('cat_t', 'SELECT'), current_user = session_user, current_schema(), current_database() IS NOT NULL",
      "SELECT table_name, table_type FROM information_schema.tables WHERE table_schema = 'sql_parity' ORDER BY table_name COLLATE \"C\"",
      "SELECT constraint_name, constraint_type FROM information_schema.table_constraints WHERE table_schema = 'sql_parity' ORDER BY constraint_name COLLATE \"C\"",
      "SELECT relkind, relpersistence, relhasindex FROM pg_class WHERE relname = 'cat_t'",
      "SELECT nspname FROM pg_namespace WHERE nspname IN ('sql_parity', 'public', 'pg_catalog') ORDER BY nspname COLLATE \"C\"",
      "SELECT typname, typtype, typcategory FROM pg_type WHERE typname IN ('int4', '_int4', 'jsonb', 'cat_t') ORDER BY typname COLLATE \"C\"",
      "SELECT proname, pronargs, prorettype::regtype FROM pg_proc WHERE proname IN ('lower', 'jsonb_set') ORDER BY proname COLLATE \"C\", 2",
    ],
  },
  {
    name: 'syntax and resolution errors',
    statements: [
      'SELEC 1',
      'SELECT 1 +',
      'SELECT * FROM',
      'SELECT "unterminated',
      "SELECT 'unterminated",
      'SELECT no_such_column',
      'SELECT no_such_function(1)',
      'SELECT abs()',
      'SELECT 1 FROM no_such_table',
      "SELECT 'a' + 1",
      'SELECT length(1)',
      'SELECT 1 = true',
      'SELECT x.y.z.w',
      'CREATE TABLE err_t (a int, a int)',
      'CREATE TABLE err_t (a nosuchtype)',
      'SELECT * FROM (VALUES (1, 2)) v(a, b, c)',
      'SELECT count(*) FROM generate_series(1, 3) g GROUP BY g HAVING g',
      "SELECT 'abc'::varchar(2)::char(1), CAST(1 AS no_type)",
      'INSERT INTO nowhere VALUES (1)',
      'SELECT $1',
      'SELECT 1 LIMIT $1',
      'SELECT coalesce(1, \'x\')',
      'SELECT greatest(1, \'2024-01-01\'::date)',
      'SELECT ARRAY[1, \'a\']',
    ],
  },
  {
    name: 'ORM-style statements',
    statements: [
      'CREATE TABLE app_user (id serial PRIMARY KEY, email varchar(255) NOT NULL UNIQUE, name text, created_at timestamptz NOT NULL DEFAULT \'2024-01-01T00:00:00Z\', is_active boolean NOT NULL DEFAULT true, meta jsonb)',
      'CREATE TABLE app_post (id serial PRIMARY KEY, user_id int NOT NULL REFERENCES app_user (id) ON DELETE CASCADE, title text NOT NULL, views int NOT NULL DEFAULT 0, published_at timestamptz)',
      'CREATE INDEX ix_app_post_user ON app_post (user_id)',
      `INSERT INTO app_user (email, name, meta) VALUES ('a@x.io', 'Ann', '{"plan": "pro"}'), ('b@x.io', 'Bob', NULL), ('c@x.io', NULL, '{"plan": "free", "flags": [1]}') RETURNING id, email, created_at, is_active`,
      `INSERT INTO app_post (user_id, title, views, published_at) VALUES (1, 'P1', 10, '2024-02-01T08:00:00Z'), (1, 'P2', 5, NULL), (2, 'P3', 50, '2024-03-01T09:30:00Z')`,
      `SELECT "u"."id" AS "id", "u"."email" AS "email", COALESCE((SELECT json_agg(json_build_object('id', "p"."id", 'title', "p"."title", 'views', "p"."views") ORDER BY "p"."id") FROM "app_post" "p" WHERE "p"."user_id" = "u"."id"), '[]'::json) AS "posts" FROM "app_user" "u" ORDER BY "u"."id"`,
      `SELECT "u"."id", "agg"."cnt", "agg"."total" FROM "app_user" "u" LEFT JOIN LATERAL (SELECT count(*)::int AS "cnt", COALESCE(sum("p"."views"), 0) AS "total" FROM "app_post" "p" WHERE "p"."user_id" = "u"."id") "agg" ON true ORDER BY "u"."id"`,
      `WITH "posts_cte" AS (SELECT "user_id", jsonb_agg(jsonb_build_object('title', "title", 'published', "published_at") ORDER BY "id") AS "items" FROM "app_post" GROUP BY "user_id") SELECT "u"."name", COALESCE("c"."items", '[]'::jsonb) FROM "app_user" "u" LEFT JOIN "posts_cte" "c" ON "c"."user_id" = "u"."id" ORDER BY "u"."id"`,
      `SELECT "u"."email", "u"."meta" ->> 'plan' AS "plan", ("u"."meta" -> 'flags') IS NOT NULL AS "has_flags" FROM "app_user" "u" WHERE ("u"."meta" @> '{"plan": "pro"}' OR "u"."meta" IS NULL) ORDER BY "u"."id"`,
      p(`SELECT "id", "title" FROM "app_post" WHERE "user_id" = ANY($1::int[]) AND "published_at" >= $2 ORDER BY "published_at" DESC NULLS LAST LIMIT $3 OFFSET $4`, '{1,2}', '2024-01-15T00:00:00Z', 10, 0),
      p(`UPDATE "app_post" SET "views" = "views" + $1 WHERE "id" = $2 RETURNING "id", "views"`, 1, 1),
      p(`INSERT INTO "app_user" ("email", "name") VALUES ($1, $2) ON CONFLICT ("email") DO UPDATE SET "name" = EXCLUDED."name" RETURNING "id", "name", (xmax = 0) AS "inserted"`, 'a@x.io', 'Ann 2'),
      `SELECT "u"."id", EXISTS (SELECT 1 FROM "app_post" "p" WHERE "p"."user_id" = "u"."id" AND "p"."published_at" IS NOT NULL) AS "has_published", (SELECT "p"."title" FROM "app_post" "p" WHERE "p"."user_id" = "u"."id" ORDER BY "p"."views" DESC LIMIT 1) AS "top" FROM "app_user" "u" ORDER BY 1`,
      'DELETE FROM "app_user" WHERE "id" = 1 RETURNING "email"',
      'SELECT count(*) FROM app_post',
      `SELECT "user_id", count(*) FILTER (WHERE "published_at" IS NULL) AS "drafts", max("published_at") AS "last" FROM "app_post" GROUP BY "user_id" ORDER BY 1`,
      `SELECT to_json(t) FROM (SELECT id, email, created_at, is_active, meta FROM app_user ORDER BY id) t`,
      `INSERT INTO app_post (user_id, title) VALUES (999, 'orphan')`,
      `SELECT "p"."title", "u"."email" FROM "app_post" AS "p" INNER JOIN "app_user" AS "u" ON "u"."id" = "p"."user_id" WHERE "u"."is_active" = true AND lower("u"."email") LIKE '%x.io' ORDER BY "p"."id"`,
    ],
  },
];
